AlistGo/alist

- alidrive/req_bean.go
- alidrive/request.go
- server/controllers/get.go
#25 昨天提了个issue，今天想想我还是自己写一个吧。
我不会go语言，所以自己照葫芦画瓢写了一个。
利用 /file/get_download_url 设置过期时间，现在直接下载、预览、复制直链跳转的阿里云盘下载直链有效期都延长到了四个小时，对于大文件下载和电影在线预览都更友好了。
> 下载链接有效期延长到四小时

- alidrive/auth.go
- alidrive/req_bean.go
#67 已解决。阿里云盘的手机版获取到的直链不需要Referer请求头就能下载。与网页版获取直链接口多次对比发现是token不同导致生成的直链不同，不同的位置在token第二段，base64解码之后，网页版后面有{"ref":"https://www.aliyun drive.c om/"}，手机版没有，所以把刷新token改为手机版的接口。不知道能撑多久(
> 修复了因为Referer导致不能下载的问题

- bootstrap/setting.go
在右键菜单中增加了使用aria2下载的item，可以直接发送选中的文件链接到aria2，省略复制再粘贴到aria2的步骤
> feat: add aria2 support

- server/webdav/file.go
Now mimeType will always be a non-empty string, by defaulting it to "application/octet-stream".
> fix(webdav): empty mimeType

- drivers/123/123.go
- drivers/123/driver.go
- drivers/123/types.go
尝试写死md5发现，但最终结果会使上传文件etag固定（貌似服务器端不会重新计算，就不怕秒传混乱吗），秒传的机制大概是etag+size，为避免污染秒传，所以无法实现流上传
> 对123盘的部分api更新

- drivers/quark/util.go
Fix: https://github.com/alist-org/alist/issues/1291
- Parameter `same_path_reuse: true` is being used by the quark cloud drive(MacOS client).
- After setting this parameter, Upload a file with the same name to the same path will rewrite the old one.
> Support file overwriting upload for drivers/quark

- drivers/onedrive/util.go
> perf: modify onedrive upload chunk size

- drivers/all.go
- drivers/google_photo/driver.go
- drivers/google_photo/meta.go
- drivers/google_photo/types.go
- drivers/google_photo/util.go
增加对谷歌相册的支持。
谷歌相册api相当的多限制，只能支持下载和上传，其他操作基本上没了。
还有几个问题：
1. api限制上限为每次请求只能获取100个媒体（如果图库数量多的话获取速度较慢）；
2. 下载的照片非原图大小；
3. 图库照片多的话，alist前端需要开启分页，否则浏览器会挂；
可以改进的地方：
1. 谷歌相册通过ID进行获取文件，可像rclone一样虚拟一些分年份、类别的文件夹存放，防止展示数量过大。
> feat: add Google Photo support

- server/static/static.go
formerly the log is not in stderr
> fix: use utils.Log during static file router init

- drivers/mediatrack/driver.go
redirect token 一次有效，点击第二次就抛出了`400`错误。本次提交直接获取302后的真实链接返回前端
> feat:get real url for mediatrack

- drivers/123/driver.go
123 今天更新多加了一层跳转`https://web-pro.cjjd18.com/download/?params=base64encode(rawurl)`，导致ip如果不符则可能下载返回403，在服务器端处理获取rawurl
> fix(123): get real url

- drivers/smb/driver.go
- drivers/smb/util.go
Tried solutions:
1. Use `conn.Write` to check the connection, but it can not detect some of SMB error.
2. Use `d.fs.Lstat` or `d.fs.ReadDir` to check the connection, but after un-share and re-share, it will raise a panic.
```
runtime error: invalid memory address or nil pointer dereference
runtime/debug.Stack()
C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x65
github.com/alist-org/alist/v3/pkg/singleflight.newPanicError({0x7ff6792bd9c0?, 0x7ff6791878a0})
C:/Users/BoYanZh/Documents/Github/alist-org/alist/pkg/singleflight/singleflight.go:35 +0x2c
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2.1()
C:/Users/BoYanZh/Documents/Github/alist-org/alist/pkg/singleflight/singleflight.go:188 +0x3b
panic({0x7ff6792bd9c0, 0x7ff6791878a0})
C:/Program …
```
> fix(smb): remount smb before each operation

- drivers/115/util.go
In special cases, developers can pass in custom UA to solve the speed limit problem Mainly for developers calling from outside
> feat(115):put UA as a variable

- internal/aria2/monitor.go
Currently if using aria2 to download a torrent file, it does not consider seeding + active as completed, so the torrent download task only completes as aria2 stops seeding.
This commit uses seeder property of TaskInfo, and mark tasks with active status and true seeder as complete.
> feat(aria2): mark aria2 seeding as complete

- server/common/sign.go
- server/handles/down.go
- server/handles/fsmanage.go
- server/handles/fsread.go
- server/middlewares/down.go
- server/webdav/webdav.go
For now, we only sign the filename and timestamp to generate a download link. But this may cause a security problem that someone can bypass authentication to access file in other protected storage.
For example, we have two local storages protected with different password:
- /s1
- f1.txt
- /s2
- f1.txt
The two files that have the same names (content may differ) but in different storages. Let `/s1` be the root directory of user `u1` and copy the download link of `f1.txt`. The link is working with a suffix `/d/s1/f1.txt?sign=xxxxx`. Now we change `s1` to `s2` in the link, the file `f1.txt` in `s2` is successfully downloaded.
If we sign the whole file path, we can identify this path hack as invalid signature.
> fix(sign): sign the raw path

- drivers/local/driver.go
According to https://github.com/alist-org/alist/issues/2484, a webp thumb won't load. This is because imaging does not support webp (see https://github.com/disintegration/imaging/pull/100#issuecomment-514822741) So we use x/image to decode webp instead
> Fix an issue that webp thumb in local storage won't load

- drivers/webdav/driver.go
- drivers/webdav/meta.go
- pkg/gowebdav/client.go
- server/common/proxy.go
- server/webdav/webdav.go
对于第二个：
现在: https://alist.example.com/dav/file --302--> https://alist.example.com/p/file --302--> https://alist-proxy.example.com/file
期望: https://alist.example.com/dav/file --302--> https://alist-proxy.example.com/file
对于第三个：
现在: 用户 <--> alist-proxy server <--> alist server <--> webdav server 
期望: 用户 <--> alist-proxy server <--> webdav server
> 优化 webdav 后端

- server/common/check.go
修复 meta.Password 和 meta.Hide 都为空的情况下，会导致无权限访问
> fix: fix hide check to canAccess

- server/webdav/buffered_response_writer.go
- server/webdav/webdav.go
webdav驱动使用了response writer直接预先写入response。
导致后续发生错误的时候无法返回错误，且status code也无法修改。
本commit引入了response buffered writer，确认无错误发生后再写入response。
复现方法：
在任意driver中的List方法中直接返回错误
预期行为：
webdav请求返回status code为指定错误status code（如500），内容为错误内容
实际行为：
webdav请求返回status code为204；响应尾部append了错误信息。
> webdav：修复发生错误时无法修改status code并返回内容

- internal/search/build.go
- server/handles/index.go
Maybe we need to lock during the process of `search.Clear` and `search.Del` with `Running.CompareAndSwap`, just `Running.Load` is not enough.
> feat: partial update index (#2593)

- README.md
- README_cn.md
According to [https://github.com/badges/shields/issues/8671](https://github.com/badges/shields/issues/8671), shields.io change their `build` badge routes, this PR fix it.
> docs: fix badges on `README.md` and `README_cn.md` [skip ci]

- drivers/baidu_netdisk/driver.go
1. `dstDir.GetPath()`得到的是目标目录路径，并不包括文件名
2. `create`方法内会再次URL编码，因此path会被重复编码造成错误
> fix(baidu_netdisk): file copy error and file upload error

- drivers/all.go
- drivers/terabox/driver.go
- drivers/terabox/meta.go
- drivers/terabox/types.go
- drivers/terabox/util.go
增加对terabox的支持，大体上与百度网盘类似
1. 使用cookie登陆，主要是ndus字段来鉴权，官方的cookie有效期是一年左右
2. 两个download api。官方WEB端的API下载大文件时请求直链需要UA和获取下载链接时的UA一致；Crack API和百度网盘类似，可以取得不需要特定UA的下载直链
3. 经测试terabox本身应该不支持秒传
close #2825 close #2678
> feat(terabox): add terabox driver (close #2825 close #2678)

- Dockerfile
- docker-compose.yml
allows the user to modify the container time zone via the `TZ` variable.
and add `-no-cache` to prevent `apk` from writing to repository metadata.
> feat: installing `tzdata` in the docker image (#1165)

- server/common/check.go
#2993 avoid accidental passwords caused by `.*` hide all file
> fix: avoid regular expression match current directory

- drivers/aliyundrive/driver.go
- drivers/aliyundrive/meta.go
- drivers/aliyundrive/types.go
Aliyun ECS in Beijing can use internal network to accelerate upload
> feat: add aliyundrive internal upload (aliyun ECS for Beijing area only)

- drivers/google_drive/driver.go
通过添加参数acknowledgeAbuse=true，对疑似风险文件直接下载
> 修复谷歌云盘无法下载

- drivers/aliyundrive_share/driver.go
如果修改了share_id，原配置的DriveId并没有重置，会导致`No Permission to access resource File`问题
> fix(aliyundrive_share): Fixed no permission after share_id change

- internal/fs/util.go
- pkg/utils/file.go
Symbolic link is not available on Windows before Creator Update (and dev mode enabled) and FAT filesystems.
Adds fallback path for users on Windows. Still recommended to enable dev mode and use NTFS for user-mode symbolic links.
> fix(fs): copy file if symlink failed

- internal/qbittorrent/client.go
- internal/qbittorrent/monitor.go
- wait for qbittorrent to parse torrent and create task #3413
- check task state correctly
- fix path sent to `op.Put()`
> fix(qbittorrent): fix multiple bugs for qbittorrent download

- drivers/pikpak_share/driver.go
> fix(pikpak_share): change media url to content url (alist-org#3273)

- internal/qbittorrent/monitor.go
- 	delete qbittorrent task but do not delete the files before transferring to avoid qbittorrent accessing downloaded files and throw `cannot access the file because it is being used by another process` error
- parse the path correctly when the torrent contains folders
> fix(qbittorrent): fix two file transferring related bugs

- internal/qbittorrent/client.go
- internal/qbittorrent/client_test.go
- internal/qbittorrent/monitor.go
Delete qbittorrent tags when the task is done or stopped with an error to avoid leaving useless tags in qbittorrent client.
> feat(qbittorrent): also delete tags when deleting qbittorrent tasks

- server/webdav.go
A disabled user with webdav permission can use webdav normally, which is not allowed.
> fix(webdav): `disabled` is not working in webdav

- server/middlewares/auth.go
Alist tokens have constant length (i think?), so leaking length info should not be a concern for us. (`subtle.ConstantTimeCompare` returns immediately if length not equal)
Fixes #3739
> fix(security): compare auth token in constant time

- Dockerfile
This is to enable using the Docker image with different flags. E.g. `docker run xhofe/alist:latest ./alist server --data=mydata`
This used to be the behavior until #2818 changed it. This would make the image more re-usable.
> feat: allow override startup command for Docker image.

- drivers/ftp/driver.go
- drivers/ftp/util.go
Add seek/range support for files on FTP, allowing users to stream multimedia.  
Addtionally this sets a shut timeout for ftp data connection to prevent infinite wait under some extreme circumstances.
> feat(ftp): support seek/range request

- drivers/all.go
- drivers/baidu_share/driver.go
- drivers/baidu_share/meta.go
- drivers/baidu_share/types.go
- drivers/baidu_share/util.go
感谢 #2967 提供实现思路，接口来自[baiduwp-php](https://github.com/yuantuo666/baiduwp-php)。
需设置链接的surl和自己的BDUSS，可查看原作者[教程](https://www.bilibili.com/video/BV1N5411A77n)。
当前commit暂未支持高速链接和缩略图功能
> feat(drivers): add BaiduYun share link support

- drivers/115/meta.go
- drivers/115/util.go
- go.mod
- go.sum
* 升级上传 api 版本到 `v4.0`
* 增加分页大小选项，多文件用户可适当调整数值，减少api请求次数，避免被WAF拦截。
> feat: update upload api to v4.0, add pagesize option (close #3753)

- internal/bootstrap/data/setting.go
- internal/conf/const.go
- internal/qbittorrent/add.go
- internal/qbittorrent/monitor.go
- server/handles/qbittorrent.go
#3588 新增离线下载做种时间
下载完成保留qb任务和临时文件一段时间来做种。
还需前端repo增加qbittorrent_seedtime对应UI完成设置。
> feat(qbittorrent): add offline download seed time

- drivers/s3/driver.go
- server/common/proxy.go
修复了文件名中的空格会变成加号的问题。
原代码使用了url.QueryEscape，修改之后使用了url.PathEscape，会将所有字符处理为urlencoded
[我的项目](https://github.com/XZB-1248/Spark)中使用了url.PathEscape来处理文件名，一切正常
> fix: spaces in filename will be replaced with plus sign

- drivers/trainbit/util.go
Trainbit返回文件名时会进行html编码，若不做处理会显示如`&amp;`等转义串
> fix(trainbit): decode html code

- server/handles/fsread.go
When requesting api/fs/list, there is a thumb indeed, however, not in api/fs/get.
I don't know whether this is a bug or the author did this on demand.
> Fix there is no thumb when fs/get

- drivers/local/driver.go
- drivers/local/util.go
- pkg/aria2/rpc/client.go
- server/common/proxy.go
修复本地文件驱动，文件名空格变成加号的问题
当初提交#3841 时没有发现本地驱动的处理逻辑有所不同
> fix(local): filename whitespace problem

- drivers/trainbit/util.go
> fix(trainbit): display filename correctly

- internal/bootstrap/data/setting.go
- internal/conf/const.go
- server/handles/ssologin.go
add Casdoor single sign-on to alist
> feat: add Casdoor single sign-on to alist

- internal/op/driver.go
When filling in the mount path, many people will subconsciously fill in a duplicate
`Failed create storage in database: UNIQUE constraint failed: x_storages.mount_path`
Originally, I wanted to Chineseize the error message directly, but due to limited technology, I couldn’t directly Chineseize it.
**Maybe you can provide a similar case, I will study and then "try" to Chineseize some of the error prompts**
add:
> docs : Add description to mount path

- drivers/s3/driver.go
使用 s3 驱动上传时设置 `Content-Type`  为文件流的文件类型，以免 s3 使用默认的 `application/octet-stream`
Set the `Content-Type` param when uploading a file using s3 driver
> feat: set content type from stream when uploading to s3

- drivers/cloudreve/driver.go
- drivers/cloudreve/util.go
目前 Cloudreve 后端拼接请求 URL 的逻辑是 `d.Address + "/api/v3" + ...`，因此若设置服务器地址时包含了末尾 "/"，拼接后就会产生重复的 slashes。但是 Cloudreve 服务并不会自动解析去除掉多余的 slash，而是会直接 fallback 到默认的应用 HTML，并且状态码是 200。因此最终的现象就是：
- 前端文件夹内看不到任何内容
- 后端没有任何错误日志
由于观察不到任何问题相关的输出，因此排查起来较为困难。
1. 配置 v3.17.0 版本
2. 配置 Cloudreve Driver，在服务器地址处设置地址时包含末尾 "/"。如：`https://cloudreve.example.com/`
3. 在 AList 前端进入对应目录
包含该 PR 前：
包含该 PR 后：
包含该 PR 前：
```text
[GIN] 2023/05/28 - 04:11:44 | 200 |     445.607µs |  101.94.139.222 | POST     "/api/fs/list"
[GIN] 2023/05/28 - 04:11:46 | 200 |  600.665164ms |  101.94.139.222 | POST     "/api/fs/list"
```
相关 Driver 后端应该添加对返回结果是否符合预期的检查，如检查返回是否是 JSON，或者 Unmarshall 是否成功。
> feat(cloudreve): 自动移除服务器地址末尾的 "/"

- drivers/seafile/util.go
Seafile Driver 下载或上传文件时返回 500，后端 Driver 日志记录 Panic。主要问题是由于局部的 `res` 未传出，导致 `res.Body()` 结果为空，后续去除 `"` 时失败。目前采用了最小改动，建议解析结果 URL 时也通过 `req.SetResult` 直接 Unmarshall JSON 字符串。
v3.17.0
1. 设置 Seafile 后端（我测试使用的是个人版）
2. 在前端点击某个文件进行下载或预览
```text
2023/05/28 03:34:51 [Recovery] 2023/05/28 - 03:34:51 panic recovered:
runtime error: slice bounds out of range [:-1]
runtime/debug.Stack()
/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
github.com/alist-org/alist/v3/pkg/singleflight.newPanicError({0x18fdc80?, 0xc0007c0ee8})
/app/pkg/singleflight/singleflight.go:35 +0x2c
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2.1()
/app/pkg/singleflight/singleflight.go:188 +0x3b
panic({0x18fdc80, 0xc0007c0ee8})
/usr/lib/go/src/runtime/panic.go:884 +0x212 …
```
> fix(seafile): Seafile Driver 下载或上传文件时返回 500，后端 Driver Panic

- drivers/base/client.go
默认的 HTTPClient 没有配置 ProxyFromEnvironment，这导致在必须通过 proxy 访问互联网的环境无法使用。
而访问 api 使用的 resty 默认 transport 携带了 http.ProxyFromEnvironment，所以会发现目录可访问，文件无法下载。
> feat: add proxy support for download

- Dockerfile
- cmd/server.go
- docker-compose.yml
- internal/conf/config.go
- server/middlewares/https.go
- server/router.go
also fix issues mentioned by `go-staticcheck`
> feat: listen to both http & https

- drivers/aliyundrive_share/util.go
Increase the list file size for aliyunshare drive to alleviate the timeout problem when there are many files in the shared directory.
> Increase the list file size for aliyunshare drive

- server/handles/fsbatch.go
- server/handles/fsmanage.go
- server/router.go
- 将正则重命名接口修改为批量重命名接口，正则替换规则置换到前端去，确保和预览结果统一。
> fix(drivers):regexp rename error fix (close #4644)

- drivers/lanzou/driver.go
- drivers/lanzou/help.go
- drivers/lanzou/meta.go
- drivers/lanzou/types.go
- drivers/lanzou/util.go
> Feat lanzou login

- drivers/115/driver.go
- drivers/123/driver.go
- drivers/189pc/utils.go
- drivers/aliyundrive_open/upload.go
- drivers/baidu_netdisk/driver.go
- drivers/baidu_netdisk/util.go
- drivers/baidu_photo/driver.go
- drivers/mediatrack/driver.go
- drivers/mopan/driver.go
- drivers/pikpak/driver.go
- drivers/quark_uc/driver.go
- drivers/terabox/driver.go
- drivers/thunder/driver.go
- drivers/weiyun/driver.go
- internal/errs/errors.go
- internal/fs/put.go
- pkg/utils/file.go
feat(baidu_netdisk): add retry on most operations; improve stability
general: add local temp file creation checking of file size, avoid incomplete stream
Close  #4863
(cherry picked from commit fda3e5c2b48661c2a3241a52a93c8c994a4efea8)
> feat(baidu_netdisk): add retry on most operations; improve stability

- drivers/189pc/driver.go
- drivers/189pc/meta.go
- drivers/189pc/utils.go
- drivers/aliyundrive_open/driver.go
- drivers/aliyundrive_open/types.go
- drivers/aliyundrive_open/upload.go
- drivers/aliyundrive_open/util.go
- drivers/baidu_netdisk/driver.go
- drivers/baidu_netdisk/meta.go
- drivers/baidu_netdisk/types.go
- drivers/baidu_netdisk/util.go
- drivers/baidu_photo/driver.go
- drivers/baidu_photo/meta.go
- drivers/baidu_photo/types.go
- drivers/mopan/driver.go
- drivers/mopan/meta.go
- drivers/weiyun/driver.go
- drivers/weiyun/meta.go
- go.mod
- go.sum
- pkg/errgroup/errgroup.go
- pkg/utils/io.go
不得不说crypt真好用，为此优化几个常用的存储驱动
特别是百度和阿里的api真脆弱，时不时就报错
> Perf upload and cache

- internal/net/request.go
- internal/net/request_test.go
- internal/net/serve.go
- pkg/http_range/range.go
try to fix #4981:
Fixed the issue that copy tasks using multi-threaded downloaders could not be canceled
> try to fix #4981

- drivers/lanzou/help.go
- drivers/lanzou/util.go
故障：蓝奏云可以正常查看文件，但下载时报错：
```json
{
"code": 500,
"message": "failed link: failed get link: not find data",
"data": null
}
```
猜测获取文件直链的逻辑已变化，此 PR 中修复了该问题
具体细节：
请求 `https://pan.lanzoui.com/fn?xxx` 现在的返回如下：
```html
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="https://assets.woozooo.com/assets/includes/js/jquery.js"></script>
<link href="https://assets.woozooo.com/assets/img/tf.css" rel="stylesheet" type="text/css">
</head>
<body>
<div id="outime">地址超时，请刷新</div>
<div class="load" id="tourl">
文件加载中...
</div>
<script type="text/javascript">
var wsk_sign = 'c20230818';
var aihidcms = '9AiH';
var iucccjdsd = '';
var ws_sign = 'c20230818';
var sasign = 'xxxxxx';
var ajaxdata = '?ctdf';
//$.ajax({
//type : …
```
> fix(lanzou): download not find data

- drivers/aliyundrive_open/upload.go
(cherry picked from commit 88f815979ac91caa8bc425a2ff9a18bbd8a2e736)
> feat(aliyun_open): fix date format

- drivers/139/types.go
- drivers/139/util.go
- drivers/189pc/driver.go
- drivers/189pc/meta.go
- drivers/189pc/utils.go
- drivers/baidu_netdisk/driver.go
- drivers/baidu_photo/driver.go
- drivers/baidu_photo/types.go
- drivers/mopan/driver.go
- drivers/mopan/util.go
- drivers/pikpak/driver.go
- drivers/pikpak/types.go
- drivers/thunder/driver.go
- drivers/thunder/types.go
- drivers/weiyun/driver.go
- pkg/utils/hash.go
- pkg/utils/hash/gcid.go
1.百度全面封禁秒传,不知道这个接口能用多久,受此影响一刻相册秒传无法实现
2.天翼云盘的新接口暂未找到秒传方法,旧接口小文件延长太大所以为按需启用
> Adaptation feature

- drivers/115/driver.go
115驱动中一直修改`resty client`的`UserAgent`，产生了数据竞争；在多线程情况下会导致`resty`处理`request header`时产生`fatal error`导致`crash`。
```
fatal error: concurrent map iteration and map write
goroutine 48178 [running]:
github.com/go-resty/resty/v2.parseRequestHeader(0xc0006fe000, 0xc000d42680)
/root/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/middleware.go:104 +0x87
```
> 修复115驱动数据竞争导致的crash

- internal/bootstrap/data/setting.go
- internal/conf/const.go
- server/handles/ssologin.go
- server/router.go
to support certain services like microsoft personal account
besides, dingtalk can use the native in-app auth with the redirect method
https://github.com/alist-org/alist-web/pull/113
> feat: sso compatibility mode

- drivers/crypt/driver.go
- drivers/crypt/meta.go
When we set a crypt driver inside alist, all the files will be encrypted and stored inside the remote backend, and this means there is no useful thumbnails provided by the remote backend. This can be inconvenient when we have large video/image files stored in the cloud with end-to-end encryption because we can not peak the content of those encrypt files in both the remote backend and alist frontend.
This feature make sure the alist frontend can load the thumbnail for those large video/image files when the option is on and thumbnails pre-generated and uploaded to the same level sub-directory `.thumbnails`, e.g. file `/decrypt/A.mp4` have thumbnail file `/decrypt/.thumbnails/A.mp4.webp`, both the original file and thumbnail will be encrypted and uploaded the remote cloud storage, e.g file …
> feat: crypt driver can load pre-generated thumbnails under the subdirectory

- drivers/terabox/util.go
> fix(terabox): encode parameters for `filemanager` api

- drivers/onedrive_app/util.go
添加onedriveApp时，如果选择cn（世纪互联）的时候会报错，参数不能固定啊
> fix: OnedriveAPP will report  error when using cn

- drivers/115/driver.go
- drivers/115/meta.go
> fix(115):limit request rate

- drivers/webdav/util.go
- pkg/gowebdav/client.go
Some webdav servers, such as Nextcloud, are much faster when using cookies for authentication after the initial authentication, compared to re-authenticating with each request.
some tests:
Without using cookies, each request on my machine takes about 2 seconds.
When using cookies, each request after basic authentication takes approximately 200-400 milliseconds.
> perf(webdav): support for cookies on webdav drive

- drivers/115/util.go
> fix(115): fix driver package import and variable

- drivers/aliyundrive_open/driver.go
I conducted small-scale tests, which seem to have no significant negative impact. If the 15-minute issue still occurs, further measures will be needed. Methods like local proxy can be attempted.
我进行了小范围的测试，看上去并没有重大负面影响，如果还是出现15分钟问题，则需要进一步措施。可采取本地代理等方法尝试。
我在阿里Open驱动降低了发起请求的有效期时间为900s=15min，同时设置内部有效期基数为1小时->12分钟
> fix(aliyundrive_open):Mitigation measures for AliOpen's 15-minute limit.

- drivers/crypt/driver.go
- drivers/crypt/meta.go
I tried adding a show hidden option for Crypt Storage. 
This is like the option to show files or directories that start with dot in Local Storage.
This is for directories that don't need to be visible to certain users.
I think it requires a .json file by running the alist lang command, but I don't know the exact workflow, so I'm just implementing the feature and submitting it.
Please confirm.
> add show hidden option for crypt storage

- server/webdav/webdav.go
Refer to #5491 使用litmus进行检测，当前版本结果:
参考[RFC 4918](https://datatracker.ietf.org/doc/html/rfc4918)
1. 根据RFC 4918 9.3.1: `405 (Method Not Allowed) - MKCOL can only be executed on an unmapped URL`
2. 根据RFC 4918 9.3.1: `409 (Conflict) The server MUST NOT create those intermediate collections automatically`
根据如上两条，添加了对应的error handling代码，修改后检测结果如下：
另外，修改了`webdav.go`中`handleLock`函数的一段错误处理代码，原为:
```go
reqPath, status, err := h.stripPrefix(r.URL.Path)
reqPath, err = user.JoinPath(reqPath)
if err != nil {
return 403, err
}
if err != nil {
return status, err
}
```
第二个if判断永远不会有机会执行到，修改为:
```go
reqPath, status, err := h.stripPrefix(r.URL.Path)
if err != nil {
return status, err
}
reqPath, err = user.JoinPath(reqPath)
if err != nil {
return 403, err
}
```
> add error handling for webdav mkcol according to RFC 4918

- README.md
- README_cn.md
- README_ja.md
- drivers/all.go
- drivers/ilanzou/driver.go
- drivers/ilanzou/meta.go
- drivers/ilanzou/types.go
- drivers/ilanzou/util.go
> feat: add ilanzou driver

- .github/workflows/build_docker.yml
- .github/workflows/release_docker.yml
- Dockerfile
- Dockerfile.ci
- build.sh
- entrypoint.sh
Compiling Golang in QEMU is not very efficient, and parallel compilation can lead to insufficient memory, resulting in extensive use of swap. Using Golang's cross-compilation to directly compile binaries for various architectures not only avoids the aforementioned issues but also eliminates the need for multiple downloads of dependencies.
This is a test of the action's execution status. In this CI run, in addition to the content of the current pull request, ffmpeg was also installed, resulting in a total duration of 7 minutes and 4 seconds: https://github.com/Mmx233/alist/actions/runs/7396976799/job/20123220627
> Improve: make docker release 10 times faster

- drivers/chaoxing/types.go
- drivers/chaoxing/util.go
手机端超星上传小组云盘和网页端上传的文件在获取文件信息（`pc/resource/getResourceList&recType=2`）时返回的 json 格式不同，`size` 和 `puid` 字段可能是 string 也可能是 int。
用自定义数据类型 `int_str` 和 `unmarshaler` 接口来解决此问题。
> fix(chaoxing):fix JSON parsing error in `content` field

- drivers/all.go
- drivers/quqi/driver.go
- drivers/quqi/meta.go
- drivers/quqi/types.go
- drivers/quqi/util.go
- go.mod
- go.sum
添加 `曲奇网盘` 存储驱动
曲奇网盘：https://quqi.com/
存储配置参数：
- phone: 手机号
- password: 密码
- cookie: cookie凭据；若填写了cookie，则不必填写手机号和密码。**推荐使用cookie方式进行验证，可保持多终端同时在线使用**
功能局限：
- 不支持302重定向访问资源
- 未实现put文件上传功能
关联issue:
- #5251 
- #840
> feat: add `quqi` driver

- drivers/google_photo/driver.go
- drivers/google_photo/util.go
`=dv`的参数获取的视频不支持流式传输，但`=m37`这种指定转码分辨率参数获取的视频是支持的。
添加了通过`mediaMetadata`中的长宽来判断分辨率。
`1080p`添加`=m37`;
`720p`添加`=m22`;
`360p`添加`=m18`;
非上述三种分辨率的标准长宽情况则默认为`=dv`.
关联issue:
- #5703
> fix(google_photo): add support for streaming video, range requests

- drivers/quqi/driver.go
- drivers/quqi/types.go
- drivers/quqi/util.go
上传文件时，若曲奇云端存在相同的文件信息摘要(md5/sha)，则不必进行实际上传，曲奇会自动创建或恢复文件；`/api/upload/v1/file/init`接口会返回文件的`node_id` `node_name` `parent_id`，且`exist`为true，并不再返回上传接口的token
以下为两种不同情况下的`/api/upload/v1/file/init`接口响应
- 曲奇云端已存在：
- 曲奇云端不存在：
> fix(quqi): error returned when uploading a file that existed

- drivers/quqi/driver.go
- drivers/quqi/types.go
- drivers/quqi/util.go
曲奇资源链接分为下载链接和预览链接，非VIP用户无法获取媒体资源文件(视频/图片等)的预览链接，只能获取下载链接
解决方案：先从`/api/doc/getDoc`接口获取预览链接，若无法获取则从`/api/doc/getDownload`接口获取下载链接。经过初步测试，预览链接的内容下载速度会比下载链接的快。
限制：非VIP用户同时下载的资源数量存在限制，超过限制后一定时间内禁止下载
> fix(quqi): empty file link for no vip user

- drivers/quqi/driver.go
- drivers/quqi/meta.go
- drivers/quqi/types.go
- drivers/quqi/util.go
- go.mod
- go.sum
特性：
- 可通过存储配置开启CDN选项，提升VIP用户单连接下载速度，解决非VIP用户下载连接数限制问题。**cdn内容需要解密，将会占用一定计算资源**
修复：
- 手机号登录时产生的Cookie保存在存储配置中，导致Cookie失效时无法登录
> feat(quqi): add download link by quqi cdn

- drivers/dropbox/driver.go
- drivers/dropbox/meta.go
- drivers/dropbox/types.go
- drivers/dropbox/util.go
Just started using this tool recently, it's a great project!
Still not very familiar with the codebase or golang, feel free to provide feedback and suggestions.
It's been quickly tested with my Dropbox Business account manually, now it's able to see teams folders.
Related to https://github.com/alist-org/alist/issues/5126 and https://github.com/alist-org/alist/discussions/5760
Sending Dropbox API request without a `Dropbox-API-Path-Root` header defaults to user home namespace.
To access Dropbox Team Space, proper namespace needs to be provided.
Namespace IDs can be obtained from `/2/users/get_current_account`.
For non-business users, `root_info.root_namespace_id` and `root_info.home_namespace_id` seem to be identical values.
For Business users, setting `root_namespace_id` in …
> feat(dropbox): add root_namespace_id to access teams folder

- server/webdav/prop.go
> fix: WebDAV's creation data should be in RFC3339 format

- .github/workflows/build_docker.yml
- .github/workflows/release_docker.yml
- Dockerfile.ffmpeg
Add docker image release with ffmpeg installed. The new images will have the suffix `-ffmpeg` such as `latest-ffmpeg` and `v3.30.0-ffmpeg`. [Test Action](https://github.com/Mmx233/alist/actions/runs/7947695437/job/21696836480) ; [Test Images](https://hub.docker.com/repository/docker/mmx233/alist/tags)
> Add docker image with ffmpeg release

- go.mod
- go.sum
- internal/bootstrap/data/setting.go
- internal/conf/config.go
- internal/search/import.go
- internal/search/meilisearch/init.go
- internal/search/meilisearch/search.go
- pkg/utils/slice.go
> feat(search): search with meilisearch.

- internal/bootstrap/data/setting.go
- internal/model/setting.go
The PR closes #6100 by replacing `polyfill.io` w/ `fastly-polyfill.io`.
----
`polyfill.io` was acquired by **a China-based CDN company** "Funnull", see [the announcement from the `polyfill.io` domain owner's Twitter](https://x.com/JakeDChampion/status/1761315227008643367) and https://github.com/polyfillpolyfill/polyfill-service/issues/2834. Despite Funnull's claims of operating in the United States, the predominance of Simplified Chinese on its website suggests otherwise, and it turns out that **"Funnull" is notorious for providing service for the betting and pornography industries**.
[The original creator of the `polyfill.io` has voiced his concern on Twitter](https://twitter.com/triblondon/status/1761852117579427975). And since the acquisition, numerous issues have emerged …
> refactor(setting): replace `polyfill.io`

- drivers/seafile/driver.go
- drivers/seafile/meta.go
- drivers/seafile/types.go
- drivers/seafile/util.go
Add multiple features:
1. Support accessing encrypted libraries in Seafile.
2. It is no longer mandatory to fill in the `RepoId`, support displaying all libraries, and keep the configuration compatible.
3. Support copying and moving between different libraries.
Changes to document: https://github.com/alist-org/docs/pull/333
添加多个功能：
1. 支持访问 Seafile 加密库
2. 可以不再必填资料库ID，支持展示所有资料库，配置保持兼容
3. 支持在不同资料库间复制、移动
改动较多，不过我仔细测了各种不同配置下的各个功能，应该没什么问题。
最开始添加这个 Seafile 驱动的这位 @wangzexi 可以看一下。
文档的改动：https://github.com/alist-org/docs/pull/333
> feat(seafile): improve features, support access to encrypted library, etc

- internal/bootstrap/data/user.go
- server/handles/user.go
Logspam because of parsing empty string in json.Unmarshal, resulting in console logging "Unexpected End of Json"
> fix: webauthn logspam

- README.md
- README_cn.md
- README_ja.md
I use https://github.com/remarkjs/react-markdown and tailwindcss to render the README file in a website, but the height attribute not works fine, like follows:
But width attribute works fine. So, I prefer to use this.
> style: use width instead of height to adapt to different rendering framwork

- drivers/189pc/driver.go
- drivers/aliyundrive_open/upload.go
- drivers/crypt/driver.go
- internal/model/obj.go
- internal/stream/stream.go
For crypt driver, skip rapid upload for supported drivers (currently only `aliyundrive_open` and `189pc`).
Avoid copying full encrypted file to temporary storage, potentially save a lot of time for large files.
> feat(crypt): force stream upload for supported drivers

- drivers/189pc/driver.go
- drivers/189pc/help.go
- drivers/189pc/meta.go
- drivers/189pc/types.go
- drivers/189pc/utils.go
- pkg/utils/time.go
为189云盘增加个人云使用`家庭云中转选项`，方便不开会员且家庭云空间小情况下大量上传。
注：旧的上传接口家庭云依然会限制上传量，所以`秒传选项`和`旧的上传方式`不生效
> feat(189pc): add family transfer upload

- internal/conf/config.go
related: #6060 
按照作者的意图，配置的对应环境变量应当是
```
MEILISEARCH_HOST
MEILISEARCH_API_KEY
MEILISEARCH_INDEX_PREFIX
```
但是原先写法中错误将`envPrefix`写成了`env`，所以上述形式的meilisearch环境变量配置无法被解析
ref: https://github.com/caarlos0/env/blob/4f6bb22b03e366362642bc1b1b2bb8ba5b5786ef/env.go#L149-L159
> fix: 修复Meilisearch相关配置无法通过环境变量配置

- drivers/seafile/meta.go
- drivers/seafile/util.go
Fixes #5302 
Seafile 驱动本身使用 username 和 password 获取 token，这对于部分单点登录的用户来说无法使用
这一 PR 在驱动中添加了 Token 字段，对于填写了 token 的用户可以跳过获取 token 这一步
注：这是我人生第一次交 PR，有什么不对的轻喷
> feat: Add token login for Seafile

- drivers/cloudreve/driver.go
Fixes #6265
从 Cloudreve 的较新版本获取到的链接是不完整的，其中不包含域名。这会导致下载时访问 `{Alist网址}/api/v3/file/download/*` 而不是 `{Cloudreve网址}/api/v3/file/download/*`，这一 PR 在获取到的链接前添加了域名。
> fix: correct the download url got by Cloudreve driver

- internal/bootstrap/storage.go
- internal/db/storage.go
加密存储依赖于远端存储，如果加密存储先于远端存储初始化就会导致初始化失败。如果按Storage.Order顺序初始化，可以将加密存储的order设置一个大一点的值，这样就不会失败了
> 使存储初始化顺序可控，防止加密存储初始化失败

- drivers/123_share/driver.go
- drivers/123_share/meta.go
- drivers/123_share/util.go
- 合并了 123 driver 的一些变动，现在 123_share driver 能够正常使用了
- 加上access token，现在能够解析大文件了
- 分享链接密码改为可选
> feat(123_share): add access token

- drivers/123/driver.go
- drivers/189pc/utils.go
- drivers/aliyundrive/driver.go
- drivers/aliyundrive_open/upload.go
- drivers/baidu_netdisk/driver.go
- drivers/baidu_photo/driver.go
- drivers/chaoxing/driver.go
- drivers/ilanzou/driver.go
- drivers/mediatrack/driver.go
- drivers/pikpak/util.go
- drivers/quark_uc/driver.go
- drivers/smb/util.go
- drivers/thunder/util.go
- internal/net/request.go
- internal/net/serve.go
- internal/net/util.go
- internal/stream/stream.go
- pkg/gowebdav/client.go
- pkg/utils/file.go
- pkg/utils/hash.go
- pkg/utils/hash_test.go
- pkg/utils/io.go
Using io.CopyBuffer can reduce the resource consumption caused by multiple memory allocations and appropriately increase the buffer size to optimize the performance of Copy.
This may mitigate the issue described in #6325
> Perf: use io copy with buffer

- drivers/onedrive/driver.go
- drivers/onedrive/types.go
- drivers/onedrive/util.go
onedrive 的文件时间应该是 `filesysteminfo.createdDateTime/lastModifiedDateTime` (文档: [filesysteminfo](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/resources/filesysteminfo?view=odsp-graph-online))，而根对象的 `createdDateTime/lastModifiedDateTime` 是指此文件在 onedrive 存储的时间
> fix(onedrive) fix Ctime/Mtime

- .github/workflows/build_docker.yml
- .github/workflows/release_docker.yml
- Dockerfile.ci
- build.sh
[test action (RUN 2)](https://github.com/Mmx233/alist/actions/runs/8820740731)
+ During the docker build process, download and generate all files changes to the `/build` directory.
+ Caching the musl library.
+ Bump action/setup-go to v5.
> CI: cache musl library in docker build workflow

- internal/op/storage_test.go
In TestGetStorageVirtualFilesByPath() and TestGetBalancedStorage(), setupStorages() was being called twice, leading to a "UNIQUE constraint failed" error.
> fix(test): ensure setupStorages is executed once

- drivers/sftp/driver.go
- drivers/sftp/util.go
This commit can close #6403 .
I have tested locally, it seems works.
> fix(sftp): reconnect to server when connection was broken (close #6403)

- drivers/all.go
- drivers/thunderx/driver.go
- drivers/thunderx/meta.go
- drivers/thunderx/types.go
- drivers/thunderx/util.go
添加 `迅雷X` 存储驱动
从原 `迅雷` 存储驱动上修改参数得来
具体配置项可参考 `迅雷`存储引擎
与原 `迅雷` 存储引擎不同的是 
存储配置参数方面：
- Username: 由原来的 `手机号` 改为 `邮箱`
- Captcha token: 现在无需手动填写
存储配置参数方面：
- Username: 由原来的 `手机号` 改为 `邮箱`
---
已知问题：
- 官方目前暂未开放上传功能，无法上传
> feat: add supports for thunderX driver

- drivers/alias/driver.go
- drivers/alias/meta.go
- drivers/alias/util.go
- internal/errs/errors.go
此PR对 alias别名 驱动进行修改
* 支持 `重命名` 和 `删除` 操作，遇到同名时 优先级的处理跟 `下载` 一致
* 修复在 #6474 中提到的问题
> feat(alias): support Rename and Remove

- drivers/mega/driver.go
- drivers/mega/meta.go
close #6226 
add 2FA support for mega, also a pr for alist-web  alist-org/alist-web#175
> add 2FA support for mega

- drivers/139/meta.go
- drivers/alias/meta.go
- drivers/alias/util.go
- drivers/alist_v3/meta.go
- internal/driver/config.go
- internal/model/storage.go
- internal/op/driver.go
- server/common/proxy.go
- server/handles/down.go
- server/webdav/webdav.go
此PR增加一个`proxy_range`选项，需要先启用 web代理 或者 webdav本地代理 才会生效
* `139Yun` 驱动开启这个选项后，可解决即使开启代理但下载链接没有返回正确的http状态码导致的一些问题，例如视频无法播放、不支持断点续传等
*  `Alias` 驱动添加是为了满足某些场景，例如 `139Yun` 走302， 然后通过 开启代理的 `Alias` 后，下载用 `139Yun` 走302，播放视频用 开启代理的 `Alias`，减少不必要的负载
*  `AList V3` 驱动添加是为了 服务器的alist挂载 `139Yun` 走302，然后本地的alist通过 开启代理的 `AList V3` 挂载 服务器的alist 播放视频等，达到不消化服务器流量的目的，移动卡还能免流
> feat: add `proxy_range` option for `139Yun` `Alias` `AList V3`

- drivers/alist_v3/driver.go
- drivers/alist_v3/util.go
> fix(alist_v3): 上传改用 `net/http`

- drivers/ftp/driver.go
- drivers/ftp/meta.go
- go.mod
- go.sum
使用 `"github.com/axgle/mahonia"` 库进行了编码转换，使得连接不支持 UTF-8 的 FTP 服务器时，可以自选编码（如 gbk）。
fixed #1260
> FTP 自定义编码支持 / Add FTP Encoding Support

- drivers/alias/driver.go
- drivers/alias/util.go
- internal/fs/list.go
- internal/model/args.go
- internal/op/fs.go
此PR修复`alias`驱动的以下bug
* 刷新文件列表时无法刷新`映射目标的文件列表`
* 开启`保护同名`时，可能会误报`ObjectNotFound`
> fix(alias): Support forced refresh of file list

- .github/ISSUE_TEMPLATE/config.yml
- README.md
- README_cn.md
- README_ja.md
我注意到您的仓库已经更改为alist-org所有，虽然GitHub提供了仓库重定向，但它毕竟与准确的仓库地址有差别。
我亦会在其他相关项目中提交PR，这是在主页下方点击“由 AList 驱动”时发现的。
相关的PR还包括：
* https://github.com/alist-org/alist-web/pull/142
此外，文档中依然有很多没有更改的链接，您觉得有必要对过往的文档进行更改吗？
> docs: change outdated repository link to alist-org

- drivers/ilanzou/driver.go
- drivers/ilanzou/util.go
The driver failed to mount due to incorrect URL parameter ordering which the backend did not accept
This commit reorders the parameters to meet the backend's expectations
and ensures successful mounting of the iLanZou driver.
Closes #6271, Closes #6415
> fix(drivers/iLanZou): resolve resource access issue on iLanZou drive

- drivers/thunder_browser/driver.go
- drivers/thunder_browser/meta.go
- drivers/thunder_browser/util.go
- 新增功能
-  添加了自动生成 `UserAgent` 功能 
- 改动部分
- 改进了`Device ID` 的生成方式 
- ` 迅雷浏览器专家版（ThunderBrowserExpert）`驱动 中的 `UserAgent`  和 `DownloadUserAgent` 变为可选填入，留空则自动生成
- 跟随官方APP，更新了部分参数：`ClientVersion`、`Algorithms`
- `迅雷浏览器（ThunderBrowser）`驱动 现在也可以使用302模式
- 修复内容
- 修复了 `删除方式选项（RemoveWay`） 选项未正确生效的问题 
- 修复了 `超级保险箱` 的密码报错信息
> feat(thunderBrowser): add automatically generate UserAgent

- drivers/pikpak/driver.go
- drivers/pikpak/types.go
- internal/offline_download/all.go
- internal/offline_download/pikpak/pikpak.go
- internal/offline_download/pikpak/util.go
- internal/offline_download/tool/add.go
- internal/offline_download/tool/download.go
- 添加PikPak网盘之后，可以在挂载目录及其子目录下使用离线下载功能，支持的链接：`magnet`, `http`, `ed2k`，也支持Twitter、TikTok、Facebook、TG 的网址链接
- 不支持在其他类型网盘目录下使用PikPak离线功能，想要保存到其他位置可以手动复制
Closes #6632
> feat: add pikpak offline download function

- go.mod
- go.sum
- server/s3/backend.go
This PR has 2 Commits:
* Fix the bug Alist S3 Implementation not support multi-level objectName(like aaa/bbb.txt) when PutObject.
* Upgrade gofakes3 to v0.0.5, which already supported AWS Signature V2.
Already tested by Seafile + Alist S3 + AliyunOpen backend storage.
> Fix S3 Implementation bug & Support AWS Signature V2

- internal/bootstrap/data/setting.go
The CDN service polyfill.io has recently been unavailable, and it [has been found to be used in implementing supply chain attack](https://www.origina.com/blog/security-alert-polyfill-io-supply-chain-attack), [related issue in polyfill repo](https://github.com/polyfillpolyfill/polyfill-service/issues/2892). The [GitHub repo](https://github.com/polyfillpolyfill/polyfill-service) of the polyfill service will now show a warning alert.
This PR changes the default polyfill url to use [cloudflare alternative endpoint](https://blog.cloudflare.com/polyfill-io-now-available-on-cdnjs-reduce-your-supply-chain-risk), which can reduce the supply chain risk.
> chore: update polyfill URL due to service unavailability and supply chain attack risk

- internal/stream/stream.go
Additionally, this resolves the issue where S3's PutObject returns a 500 status code, as seen in:
https://github.com/alist-org/alist/blob/9e0482afbb0d3490cf3d98d79fbd0f75b9ac6349/server/s3/backend.go#L315-L319
It also mitigates log spam caused by repeated file closures, detailed here:
https://github.com/alist-org/alist/blob/9e0482afbb0d3490cf3d98d79fbd0f75b9ac6349/internal/op/fs.go#L501-L505
Already tested by Alist S3 + restic S3 + 123pan
> fix: ignore os.ErrClosed error on repeated FileStream close operations

- drivers/pikpak/driver.go
- drivers/pikpak/types.go
- drivers/pikpak/util.go
- `Link`函数现在使用新的`request`函数发送请求
- 初始化时获取`UserID`
- 自动生成 `DeviceID` 
- 自动生成 `UserAgent`
- 自动生成 `CaptchaToken`
- 添加了新的`request`函数，携带`CaptchaToken`、`DeviceID`、`UserAgent`
- 修复了`Link`函数返回下载地址无效的问题，现在可以正常播放和下载
> fix(pikpak): add captcha_token generation function

- drivers/all.go
- drivers/onedrive_sharelink/driver.go
- drivers/onedrive_sharelink/meta.go
- drivers/onedrive_sharelink/types.go
- drivers/onedrive_sharelink/util.go
This driver is intended to simulate the web API request when accessing a OneDrive Business ShareLink using a web browser. 
As a result, the 302 redirect will not be available, because the downloading link require a vaild header.
The cron to refresh the header per hour is enough to my experience. If you meet errors, consider to set it to a lower value.
This is also beneficial in preventing abuse of OneDrive Business. 
It's even usable in the CN region (SPO operated by 21Vianet), but it's not promised.
> feat: add support for Onedrive Sharelink driver

- drivers/123/driver.go
- drivers/123/types.go
- drivers/123/util.go
Fixes an issue where using `file_name` order could result in incorrect file counts compared to response fields.
As shown in the image below, the actual number of files in the root directory is 3, but the API's response field indicates 4. In another directory, the actual file count is 933, yet the API has returned only 787 files.
After switching to a different sorting method, everything works correctly. Therefore, I've only added a warning here.
> fix(123pan): add warning for mismatched file count when listing files

- drivers/lanzou/driver.go
- drivers/lanzou/meta.go
- drivers/lanzou/util.go
修复： #6857
问题原因： 蓝奏云屏蔽User-Agent（直接屏蔽不会误杀吗？
修复方案：允许指定User-Agent
> fix(lanzou):not find file page param

- internal/bootstrap/data/setting.go
- internal/db/meta.go
- internal/db/settingitem.go
- internal/db/storage.go
- internal/db/user.go
- internal/db/util.go
- internal/model/setting.go
此PR解决以下问题
* 数据库为`mysql`时，修改数据时会按照 表的第一列 排序，导致 `alist-web` 设置页乱序
* 数据库为`postgres`时，修改数据时会追加到最后一行，导致 `alist-web` 存储 、用户、元信息页乱序
> 修复：数据库不是sqlite3时会乱序的bug

- drivers/all.go
- drivers/lenovonas_share/driver.go
- drivers/lenovonas_share/meta.go
- drivers/lenovonas_share/types.go
- drivers/lenovonas_share/util.go
> 链接示例： https://siot-share.lenovo.com.cn/s/#/Ss.JjMaJJwcgrDT46qhVA
> 提取码：fr0w
+ `ShareID`  分享链接中末尾的字符串  `Ss.JjMaJJwcgrDT46qhVA`
+ `SharePwd` 提取码
+ `Host` 链接前缀，默认为 `https://siot-share.lenovo.com.cn`，局域网中可以用 `http://192.168.1.XX`
> feat: add support for lenovonas_share driver

- server/common/auth.go
- server/handles/auth.go
- server/router.go
closes https://github.com/alist-org/alist/issues/6792
> feat: invalidate token on logout

- drivers/thunder_browser/driver.go
- drivers/thunder_browser/meta.go
- drivers/thunder_browser/types.go
- drivers/thunder_browser/util.go
- 改进了 `space` 参数的识别方式
- 跟随官方APP，更新了部分参数
> fix(thunder_browser): fix fix space parameter not handled correctly in some cases & update some parameters

- go.mod
- go.sum
- internal/bootstrap/config.go
- internal/bootstrap/data/data.go
- internal/bootstrap/data/task.go
- internal/bootstrap/task.go
- internal/conf/config.go
- internal/db/db.go
- internal/db/tasks.go
- internal/fs/copy.go
- internal/model/task.go
- internal/offline_download/tool/add.go
- internal/offline_download/tool/download.go
- internal/offline_download/tool/transfer.go
- internal/offline_download/tool/util.go
closes https://github.com/alist-org/alist/issues/5313
> feat: Persistant Task

- drivers/115/driver.go
- go.mod
- go.sum
- internal/offline_download/115/client.go
- internal/offline_download/all.go
- internal/offline_download/tool/add.go
- internal/offline_download/tool/download.go
* 增加115的离线下载工具，仿照pikpak的写法实现
* 由于115自己维护一个离线下载列表，可能会发生不同步的问题
* 目前当下载成功后，删除离线列表中完成的任务
* 已知问题： 115已经在离线列表中的任务url不能再次添加
> feat(115): add offline download tool (close #6888)

- drivers/chaoxing/types.go
change the data type on deserializing json
> fix: upload to ChaoxingxingGroupCloud failed

- drivers/all.go
- drivers/quark_uc_tv/driver.go
- drivers/quark_uc_tv/meta.go
- drivers/quark_uc_tv/types.go
- drivers/quark_uc_tv/util.go
- 新增 夸克网盘TV端驱动 和 UC网盘TV端驱动
- 使用了TV版的接口
- **现在可以使用 302方式 进行播放/下载**
- 只能访问（List）、下载（Link），其他操作均不支持（接口不支持)）
1.  添加驱动时，无需填写任何字段：
2.  保存后，右上角弹出提示框：
3.  此时，返回驱动页面，如下图所示：
4. 使用对应的客户端APP进行扫码登陆，登陆完成后，禁用刚刚添加的驱动，再启用该驱动：
5. 此时驱动应该正常启用，enjoy~
- `根文件夹ID`：可参考 `夸克网盘驱动` 进行填写：https://alist.nn.ci/zh/guide/drivers/quark.html
> feat: add support for quark tv driver and uc tv driver

- drivers/s3/driver.go
AWS S3 presigned URL is not available in all AWS regions. This PR allows the S3 driver to directly execute GetObject requests instead of using presigned URLs when settings like web proxy and WebDav native proxy are enabled.
CAUTION: This PR makes the S3 driver call `common.ShouldProxy` in internal methods. Passing a argument into `model.LinkArgs` or `context.Context` maybe a better solution. Please let me know if I should join this kind of modification.
Test Docker Image: `mmx233/alist:v3.36.0-alpha3` `mmx233/alist:v3.36.0-alpha3-ffmpeg`
> feat(s3): using internal download method in proxy

- drivers/pikpak/driver.go
- drivers/pikpak/meta.go
- drivers/pikpak/util.go
- 移除了  `oauth2`  的登录方式，改为普通请求（需要携带 `captcha_token`）
> 原因：现在使用 `oauth2` 进行登录时，会返回错误提示：
``` json
{
"error": "invalid_argument",
"error_code": 3,
"error_description": "currently not supported",
"details": []
}
```
- 跟随官方版本，更新了部分客户端参数（Algorithms）
- 为 `request` 函数添加了 `User-Agent`、`X-Device-ID`、`X-Captcha-Token` 参数
- 添加了 `refresh_token` 字段，用户可自行抓包填写，也可以留空，会自动生成
- 添加了 `captcha_token` 字段，无需手动填写
---
> 需要**点击链接**，进行滑动验证码验证，验证完成后，请**禁用添加的驱动并重新启用**，此时驱动应该正常工作
> 或者自行抓包，获取 `Refresh Token` 并填入对应字段
> fix(pikpak): fix the problem that refresh_token cannot be obtained

- .github/workflows/build_docker.yml
- .github/workflows/release_docker.yml
- Dockerfile
- Dockerfile.ci
- Dockerfile.ffmpeg
This change makes building Docker images more flexible for sub-versions or forked versions. Additionally, this PR reduces the number of Docker image layers and increases the cache hit rate for CI.
Test Images: [v3.36.0-alpha6](https://hub.docker.com/layers/mmx233/alist/v3.36.0-alpha6/images/sha256-9d9ec0de0e6da1341c63af68d08521aea5ffc96c9e7fb371fd299389c8f6d695?context=repo), [v3.36.0-alpha6-ffmpeg](https://hub.docker.com/layers/mmx233/alist/v3.36.0-alpha6-ffmpeg/images/sha256-4a0e8fdfe3de83490a8511a274444b5e72296de52393ecf6a50346b8e0c12c6a?context=repo)
Test Actions: [release_docker](https://github.com/Mmx233/alist/actions/runs/10339850804)
> ci(docker): using docker build args instead of extra dockerfile for ffmpeg

- internal/net/serve.go
观察到日志中出现以下乱码内容
```
ERRO[2024-08-14 01:12:26] http request [https://d.pcs.baidu.com/*] failure,status: 403 response:-K@0ЫLfE?A2R:1iE-ߍ$r008lʌ\a8pΥ/33ř QyQCN|M{ζzm]i
```
排查原因，判断是在处理HTTP响应时，Body是经过gzip压缩的。在这种情况下，需要先解压缩Body才能读取内容
修复后
```
ERRO[2024-08-14 01:16:07] http request [https://d.pcs.baidu.com/*] failure,status: 403 response:{"error_code":31329,"error_msg":"hit black userlist , hit illeage dlna","request_id":870*918065}
```
可正常读取body
> fix:gzip body导致的乱码

- drivers/pikpak/driver.go
- drivers/pikpak/meta.go
- drivers/pikpak/util.go
- 修复了部分错误信息未被正确处理的BUG————现在可正常显示 ~~`被风控后的滑动验证地址`~~
- 修改了 `CaptchaToken` 的处理逻辑
- 调整了 `Link` 函数的部分参数
- 现在 `DisableMediaLink` 选项将默认开启————可以避免出现 #4735 的问题
- 尝试为上传添加 `进度显示`
- 移除了 `client_id`、`client_secret` 字段
- 添加了 `DeviceID` 字段
- 添加了 `Platform` 选择项：可选 `android`、`web`
- 添加了 `Web` 端的 `ClientID`、`ClientSecret`、`ClientVersion`、`PackageName`、`WebAlgorithms`
---
- `Username`：登录邮箱
- `Password`：登录密码
- `Platform`：选择 登录平台：安卓（android）| 网页（web）
- `Refresh token`：刷新令牌——手动填写后则无需填入账号密码登录（最好还是填一下），需抓包获取或登录后自动填入
- `Captcha token`：验证码令牌——**仅需要在触发风控时填写**，具体获取方式见下文
- `Device id`：设备ID——一般情况下无需修改，根据`Username`和`Password`字段的内容进行生成
- `Disable media link`：禁用媒体链接——关闭后将使用媒体地址，可能出现无法访问非媒体文件的情况
---
- 如果出现下图情况：
说明访问过于频繁，该账号/IP将在一段时间内无法登录。
> 注意：出现此情况后，**使用第三方授权可正常登录官方客户端**。同时，**使用该IP请求任何账号都有几率再次出现此问题**，可尝试使用`Refresh …
> fix(pikpak): modify the processing logic of CaptchaToken

- drivers/pikpak_share/driver.go
- drivers/pikpak_share/meta.go
- drivers/pikpak_share/types.go
- drivers/pikpak_share/util.go
- 删去了 `Username` 和 `Password` 字段————经测试，不需要登录账号
- 添加了 `Captcha token` 生成函数
- 添加了 `Platform` 选择项：可选择 `android` 或 `web` 平台
- 添加了 `DeviceID` 字段，接口认证需要
- 添加了 `UseTransCodingAddress` 字段：默认不启用，打开后 下载地址将使用**转码后的地址**（实测 可获取 **完整的** **转码后的文件**）
---
- 打开 `UseTransCodingAddress` 选项后，无法使用 `Alist` 网页版播放视频，但**可正常下载**或**使用第三方播放器**
> 测试发现请求 `转码后的地址` 时，如果携带 `Range` 字段，则不返回内容
> fix(pikpak_share): add captcha_token generation function

- drivers/pikpak/driver.go
- drivers/pikpak/types.go
- drivers/pikpak/util.go
- 修改了上传时的配置项，现在使用 `webdav` 可正常上传
- 上传时如果遇到 `Method Not Allowed: 405 Method Not Allowed`错误
> 1. 检查 配置文件中的 `temp_dir` 所设置的目录是否存在——默认 为 `data`目录中的 `temp`目录
> 2. 检查是否 触发了 `PikPak`上传限制，非会员一天只能上传一次
> fix(pikpak):fix webdav upload issue

- internal/offline_download/http/client.go
Offline download with the SimpleHttp tool parses the filename from the requesting URL. However, if the path in the URL is empty, the filename is also empty (which is then transformed into ‘.’ by path.Base). 
If the filename is empty, TempDir is set to the filename. Alist creates TempDir successfully, but os.Create fails to create the target file. 
To resolve this, I assign a default name to the temp file based on the hostname, replacing all dots with underscores. This ensures that TempDir and the filename are never equal.
> Fix os.create failure, while the name of downloaded file is empty in offline_download

- internal/errs/search.go
- internal/op/fs.go
- internal/search/build.go
- internal/search/search.go
- pkg/mq/mq.go
- server/handles/index.go
Check Running and store true is not an atomic operation, Quit and Running will be wrong variable when StopIndex and UpdateIndex called from http api or index auto_update enabled, leading to goroutine leak, alist log is full of index log:
I removed Running variable, use Quit pointer to check BuildIndex is running, intruducing local running variable to notify WalkDir stop running, make sure only one goroutine is running BuildIndex.
> fix(search): BuildIndex concurrency error

- drivers/all.go
- drivers/kodbox/driver.go
- drivers/kodbox/meta.go
- drivers/kodbox/types.go
- drivers/kodbox/util.go
- kodbox project：https://github.com/kalcaddle/kodbox
- kodbox api：https://doc.kodcloud.com/v2/#/
Close: #7058
> feat: add kodbox storage

- drivers/local/util.go
Currently, ffmpeg outputs about 150 lines of logs for each thumbnail generation action. This PR makes ffmpeg only output logs at the error level and above.
Test Image: `mmx233/alist:v3.36.0-beta2-ffmpeg`
> chore(local): decrease mass ffmpeg logs

- internal/net/serve.go
Memory leak happens in MacOS WebDav Server. Can't reproduction in my end.
Closes #7088
Tested with image:  `mmx233/alist:v3.36.0-gamma2` `mmx233/alist:v3.36.0-gamma2-ffmpeg`. Verified in issue author's end.
> fix(webdav): memory leak in HttpServer

- internal/bootstrap/config.go
- internal/op/fs.go
fix: #7112 #7030
问题： 本地走代理时使用io.ReadSeek接口，共用一个link导致数据污染
考虑到代理时会自动调用io.Close接口，所以不使用io.ReadAt修复, 代价是可能会创建大量文件句柄。
#7030 中的网盘走代理时文件损坏无法复现，可能是 #7003 完成修复
> Fix local proxy

- drivers/baidu_photo/driver.go
- drivers/baidu_photo/utils.go
fix: #7133
以前的接口还能用，如果百度再改接口就只能用cookie登录了。
> fix:(baidu_photo): change download api

- drivers/google_photo/driver.go
#7158 During copy from google photo to aliyun, it failed consistently with 404 when copying mp4 file with =m37.
Change =m37 to =dv will fix the issue
> fix(google_photo) fix issue copy videos from google photo

- go.mod
- go.sum
- internal/conf/const.go
- internal/offline_download/all.go
- internal/offline_download/tool/download.go
- internal/offline_download/transmission/client.go
- server/handles/offline_download.go
- server/router.go
* 增加`Transmission`作为离线下载工具
* 配置界面需要前端支持
> feat(offline_download): add transmission (close #4102)

- drivers/all.go
- drivers/febbox/driver.go
- drivers/febbox/meta.go
- drivers/febbox/oauth2.go
- drivers/febbox/types.go
- drivers/febbox/util.go
#7293
官方网站：`https://www.febbox.com`
官方开放平台：`https://www.febbox.com/open`
---
- `Root folder id`：根目录ID，默认为 `0`，可从官方Web端的地址栏中获取
- <img width="376" alt="image" src="https://github.com/user-attachments/assets/50c3058d-5725-42cf-afe8-3a22668745aa">
- 如图中的 `目录ID` 为：`13168737`
- `Client id`：客户端ID，从 官方网站中生成：`https://www.febbox.com/open/clients`
- `Client secret`：客户端密钥，从 官方网站中生成：`https://www.febbox.com/open/clients`
- <img width="1044" alt="image" src="https://github.com/user-attachments/assets/23282ce2-e3b5-4f5a-bda7-2bd68bf8b456">
- **注意看清楚`client_id`和`client_secret` ，不要填反了**
- `Sort rule`：排序规则
- `Page size`：单次请求的文件列表大小，默认 `100`
- `User ip`：**可选** ，用户下载时的IP，引用官方说明
- `IP address, Optional parameter. Supports IPv6 format.After filling in, the best download server suitable for the IP location will …
> feat: add `febbox` driver

- drivers/ilanzou/driver.go
修复问题： https://github.com/AlistGo/alist/issues/7357
问题原因： 在查询完第 1 页后，没有更新 offset ，导致死循环
修复方案： 在每次查询 1 页后，更新 offset
> fix(ilanzou): fix infinite loop when getting file list

- drivers/ilanzou/driver.go
修复问题： https://github.com/AlistGo/alist/issues/7250
问题原因： 在通过`/7n/getUpToken`接口获取`token`时，如果请求传参中的文件`KB`数`fileSize`字段为0，则会报错；而对于上传小于`1024 Byte`的文件时，目前是按`1024`整除得到的结果，也就是`0`，导致无法获取到`token`，从而中断了上传流程。
修复方案： 调研了蓝奏云优享版的`/7n/getUpToken`接口，发现他们在将字节数转为`KB`数时是向上取整的，所以改成向上取整应该可以解决，避免了计算结果为`0`的情况。
> fix(ilanzou): fix upload failure for small files

- drivers/115/driver.go
- Introduce a file size restriction to handle uploads more securely.
- Provide an informative error for uploads that exceed the new limit.
> fix(115): enforce 20GB file size limit on uploadev

- .github/workflows/build_docker.yml
- .github/workflows/release_docker.yml
- build.sh
`linux/riscv64`, `linux/ppc64le` support is added to docker release.
Can't test the build result for I have no such kind of device.
Test Action: https://github.com/Mmx233/alist/actions/runs/11551964189/job/32150087995
Test Image: `mmx233/alist:v3.38.0-beta1`, `mmx233/alist:v3.38.0-beta1-ffmpeg`
> ci(docker): support riscv64 and ppc64le

- drivers/local/driver.go
- drivers/local/token_bucket.go
Token bucket of thumbnail concurrent now can migrate smoothly. The concurrent during migration will not bigger than max(new, old) now.
Test Image: `mmx233/alist:v3.38.0-alpha2`, `mmx233/alist:v3.38.0-alpha2-ffmpeg`
> feat(local): thumbnail token bucket smooth migration

- .github/workflows/release_freebsd.yml
- build.sh
the binaries support freebsd 14.1+ (amd64/arm64/i386)
> ci: add freebsd release build

- drivers/aliyundrive_open/meta.go
- internal/conf/config.go
根据最近几个月的反馈：
1. 修改阿里云盘默认类型为 `资源库`
- 很多人默认文件都在资源库，但是不是达人，然后导致添加后看不到文件 时常看到这个问题，修改默认云盘类型为资源库，不需要手动修改了
3. 以及配置文件持久化默认不启用
- 可能网络原因上传 复制等操作导致失败，不知道已经有持久化，然后占用很大本地空间，不知道什么原因，改成默认不启用，需要的自行按需启用
> refactor(aliyunopen,config): Modify default properties

- drivers/baidu_netdisk/types.go
- drivers/baidu_netdisk/util.go
- drivers/baidu_photo/types.go
- drivers/baidu_photo/utils.go
> feat(baidu_netdisk,baidu_photo): add and fix hashinfo

- drivers/115/driver.go
- drivers/115/meta.go
- drivers/115/util.go
> feat(115): enhance cache

- drivers/terabox/driver.go
- drivers/terabox/types.go
- drivers/terabox/util.go
https://github.com/AlistGo/alist/issues/7490
1. `/api/create`接口报错，返回了`errno`和`errmsg`，但`alist`没有对`errno`做判断，导致页面上误显示为上传成功；
2. 根据返回的`errno: 10`和`errmsg: "create super file failed."`，无法定位到问题，所以需查看官方接口参数；
3. 根据对`Terabox`抓包分析，在上传超过`8GB`的文件时，`chunk`大小为`16MB`，而`alist`的逻辑用的是`4MB`，可能因为`chunk`太多导致在最终的`/api/create`接口中上传失败；
4. `Terabox`还更新了`/api/precreate`接口的入参字段。
1. 对`Terabox`做了多次抓包分析，发现`chunk`的大小会按如下规则动态调整：
| 文件大小  | chunk |
| :-------------: | :-------------: |
| (0GB, 4GB]  | 4MB  |
| (4GB, 8GB]  | 8MB  |
| (8GB, 16GB]  | 16MB  |
| (16GB, 32GB]  | 32MB  |
| (32GB, 64GB]  | 64MB  |
| (64GB, 128GB]  | 128MB  |
2. 在`/api/precreate`接口中，请求体有如下变化：
其中`block_list`是固定值，用多个账号测试发现都是这个值，不再需要在这个阶段计算`chunks`的`md5`了。
3. 额外修正了`local_mtime`字段的值，改成本地文件的`mtime`，不应该传当前时间戳。
1. 9GB大文件上传成功；
2. 以下文件均上传成功。
> fix(terabox): big file upload issue

- drivers/terabox/util.go
https://github.com/AlistGo/alist/issues/7487 中第`1`个问题：如果`Terobox`的`Cookie`失效或填写错误，会在`driver Init`阶段`panic`
https://github.com/AlistGo/alist/blob/0a46979c519885465e586da009b70422382c84ac/drivers/terabox/util.go#L90C3-L90C61
1. 在`Terobox Init`进行登录时，如果当前`ip`与注册时的区域不符时，接口会返回`errno=6`然后进入这段逻辑，并根据`header`中返回的`url prefix`设置正确的`url`
2. 但是，在更换`prefix`后重新请求时，如果`Cookie`不合法，也会返回`errno=6`，导致再次进入到这段逻辑中，由于这时`header`中没有`Url-Domain-Prefix`了，导致访问`nil`的切片造成`panic`
增加非空判断，如果`Cookie`不合法则会抛出错误
> fix(terabox): panic due to slice out of range

- drivers/chaoxing/driver.go
- drivers/vtencent/drive.go
- internal/op/storage.go
https://github.com/AlistGo/alist/issues/7487 中的第`2`个问题：如果在`alist`启动时，某个`storage`的初始化过程中发生`panic`，之后删除这个`storage`时会报错：`failed get storage driver: no mount path for an storage is: XXXX`.
1. 在删除`storage`时，会去`storagesMap`中查询，如果查不到则会报错；
2. 在`initStorage`流程中，如果`storageDriver.Init()`发生了`panic`，在`recover()`中没有向`storagesMap`写入这个`storage`，所以后续的删除操作会报错。
1. 发生了`panic`时，在`recover()`中向`storagesMap`写入这个`storage`；
2. 对所有类型`driver`的`Drop`方法完善`nil`检查。
https://github.com/user-attachments/assets/b5e3c64b-b3fb-4343-9ba6-77ab05afbec8
> fix(storage): delete storage fails if a panic occurred during initialization

- drivers/pikpak/driver.go
- drivers/pikpak/util.go
- drivers/pikpak_share/driver.go
- drivers/pikpak_share/util.go
> fix(pikpak):Domain block and change to NET

- pkg/utils/random/random.go
The library `math/rand` is not suitable for high-security scenarios.
Tested with code:
```golang
package main
import (
"fmt"
"github.com/alist-org/alist/v3/pkg/utils/random"
)
func main() {
str := random.String(10)
fmt.Println(str)
}
```
Output:
```shell
IoQrBB5BR4
yDMJVfJqED
```
> feat(security): generating random string with crypto rand

- server/handles/ssologin.go
Using TOTP to control state values can cause nearly random login failures. I was shocked when I discovered it was implemented using TOTP codes. It's like a random bomb.
Test Image: `mmx233/alist:v3.39.4-beta1` `mmx233/alist:v3.39.4-beta1-ffmpeg`
> feat(sso): generate and verify OAuth state with go-cache

- drivers/local/driver.go
Fix issue when user specified for running alist is different from the owner of file(s) being copied/moved in local filesystem, causing the file(s) owner changed unexpectedly.
Optimal copy options (such as the size of copy buffer) may need further consideration , but until now it should be functional basically.
PS. We may consider using os.CopyFS (since 1.23) provided by standard library when it comes stable in the future.
> 🐛 local driver: Preserve file owner when copying

- drivers/baidu_photo/driver.go
- drivers/baidu_photo/meta.go
- drivers/baidu_photo/utils.go
token 登录下载彻底被百度修复，改为Cookie登录 fix: #7590
> fix(baidu_photo): cookie login fix download error

- drivers/pikpak/driver.go
- drivers/pikpak/meta.go
- drivers/pikpak/util.go
- 移除了 刷新令牌方法 `oauth2` 方式    
- #7545
> fix(pikpak): remove oauth2 method

- drivers/onedrive/util.go
- drivers/onedrive_app/util.go
This PR will close https://github.com/AlistGo/alist/issues/7506
把自己提的issue修了一下（
没怎么接触过GO，但改文本还是会的（
修改为500和1000的差别不大，都是1m11s左右获取完成（5841个文件）
> fix(onedrive): fix timeout error (#7506).

- internal/bootstrap/data/setting.go
- internal/conf/const.go
- server/handles/ssologin.go
This PR allows user set custom extra scope for SSO login.
The purpose of this change is to give users more flexibility of username key (`sso_oidc_username_key`) based on ID token from OIDC server, for example, using `email` or `username`. Some OIDC implementations adds extra claims to ID token based what scope are passed to the server, so allowing users customize the scope is a must.
This PR adds a new settings option, `SSOExtraScopes` (`sso_extra_scopes`). If the settings option is not empty, it will be appended to the default scopes (`[openid profile]`).
A new settings key, `sso_extra_scopes` would be added to front-end / i18n file. I have opened a related PR on front-end project: https://github.com/AlistGo/alist-web/pull/203.
There are also small typo and styles fixes should be made, …
> feat(sso): add custom extra scope support

- drivers/139/driver.go
- drivers/139/meta.go
- drivers/139/types.go
近期升级到新版个人云，被这个无法上传大文件的问题困扰。
https://github.com/AlistGo/alist/issues/7444#issuecomment-2495115410
代码首先来自 https://github.com/ykxVK8yL5L/alist/tree/main/drivers/139 ，参考了部分代码，在此向 @ykxVK8yL5L 致谢！
如果文件分片数量大于 100 个，在网页端上传会使用第二个接口 `/hcy/file/getUploadUrl` 获取上传地址，这里也加上了相关逻辑，支持分片数量超过 100。
加上选项可供用户自定义分片大小，暂未修改原来的分片大小。
- 目前网页端的分片大小为 20 MB （20971520），实测该值过小可能会拖慢大文件的上传速度，故此处提供选项供用户自行研究。
- 新版个人云所使用的 EOS 文档（<https://ecloud.10086.cn/op-help-center/api/article/40933>）中说明“无法上传大小大于 5 GB 的对象”，之前不能上传 5 GB 以上文件的原因在此，故分片大小不要超过 5 GB。
> feat(139): support multipart upload (close: #7444)

- server/handles/task.go
Add the following three API to process "do with selected tasks" requests. They accept a JSON array containing task IDs from the request body and return any errors as a "taskId: message" JSON object to the frontend through the `data` attribute of the response.
- `/api/task/${props.type}/cancel_some`
- `/api/task/${props.type}/delete_some`
- `/api/task/${props.type}/retry_some`
> perf(task): merge requests of operating selected

- server/ftp/fsup.go
刚刚pr合并的时候我还在测，结果真的就发现了两个bug，哭了。
问题1：上传大文件结束时，服务端会阻塞式地将本地的临时文件上传到网盘，期间FTP客户端会显示100%不动。这本来是预期的行为，但某些FTP客户端在这种情况下会认为上传超时失败，所以只能改成不阻塞的“以任务形式上传”
问题2：临时文件不会自动删除，而且挂载另一个AListV3时没法上传，发现是因为临时文件在`SetTmpFile`以后还得手动加入`Closers`里面，否则文件不能自动关闭。
> fix(ftp-server): large transfer leads to client timeout

- internal/net/request.go
- internal/net/serve.go
群里有人说新版本内存释放回收慢，看了下有这个改动。
[close of closed channel问题](https://github.com/AlistGo/alist/pull/7529)
关闭两次信道造成panic
[close1](https://github.com/AlistGo/alist/blob/main/server/common/proxy.go#L57)
[close 2](https://github.com/AlistGo/alist/blob/main/internal/net/serve.go#L177)
> fix(net): close of closed channel

- internal/bootstrap/data/setting.go
- internal/bootstrap/db.go
- internal/op/setting.go
- server/common/base.go
> perf: 优化非sqlite3数据库时初始化慢的问题

- internal/fs/copy.go
- internal/fs/fs.go
- internal/fs/put.go
- internal/offline_download/115/client.go
- internal/offline_download/aria2/aria2.go
- internal/offline_download/http/client.go
- internal/offline_download/pikpak/pikpak.go
- internal/offline_download/qbit/qbit.go
- internal/offline_download/tool/add.go
- internal/offline_download/tool/base.go
- internal/offline_download/tool/download.go
- internal/offline_download/tool/transfer.go
- internal/offline_download/transmission/client.go
- internal/task/base.go
- server/handles/fsmanage.go
- server/handles/fsup.go
- server/handles/offline_download.go
- server/handles/task.go
Rename `TaskWithCreator` to `TaskExtension`
Add following members into `TaskExtension`（and they will be returned when `/api/task/info` is called）:
- `startTime`: Timestamp when `Run` is called
- `endTime`: Timestamp when `Run` returned
- `totalBytes`: Total bytes to be transferred
> feat(task): add speed monitor

- drivers/139/driver.go
- drivers/139/types.go
问题描述：
- 139上传同名文件（更新）时不会覆盖现有文件，而是自动重命名添加日期。
- 这种行为不同于 Alist 中其他存储，导致自动备份工具（如Cloud Sync）频繁提示上传失败。
- 实际查看网盘后，发现存在大量带有日期标记的重复文件。
解决方案：
- 手动实现处理冲突的相关逻辑。
- 对于新个人云，创建上传信息后即可通过判断文件名得知是否冲突，随后将旧文件重命名然后删除即可。
- 对于家庭云，由于创建上传信息后无法获取自动重命名后的文件名，需要在上传前重命名并删除旧文件。
> fix(139): handle upload file conflicts

- drivers/s3/driver.go
- drivers/s3/meta.go
Add a boolean addition `EnableCustomHostPresign` to determine whether to attach the sign when using the custom host.
- Previous behavior (taking Aliyun OSS as an example):
- Download link without custom host (using internal endpoint):
```
https://<bucket-name>.oss-cn-beijing-internal.aliyuncs.com/<filename>?X-Amz-Algorithm=***&X-Amz-Credential=***...
```
- Download link within custom host (using external endpoint, the following link is **invalid**):
```
https://<bucket-name>.oss-cn-beijing.aliyuncs.com/<filename>
```
- Current behavior when `EnableCustomHostPresign` is `false`: Same as previous
- Current behavior when `EnableCustomHostPresign` is `true`:
- Download link within custom host (using external endpoint, the following link is **valid**):
``` …
```
> feat(s3): support custom host presign

- internal/db/db.go
- internal/db/sshkey.go
- internal/model/sshkey.go
- internal/op/sshkey.go
- server/handles/sshkey.go
- server/router.go
- server/sftp.go
Support log in SFTP server endpoint via public key
Add a new model `model.SSHPublicKey`
Add a database table of `model.SSHPublicKey`
Add following APIs to CRUD authorization keys:
- GET `/api/me/sshkey/list`
- POST `/api/me/sshkey/add`
- POST `/api/me/sshkey/delete`
- GET `/api/admin/user/sshkey/list`
- POST `/api/admin/user/sshkey/delete`
> feat(sftp-server): public key login

- drivers/115/meta.go
- drivers/115_share/meta.go
Change the type of `LimitRate` in 115 Cloud and 115 Share from `number` to `float`
> fix(115): support float QPS

- server/handles/webauthn.go
It shouldn't typically respond with success status when deleting WebAuthn credential fails.
> fix(webauthn): handle error when removing webauthn credential

- internal/bootstrap/data/user.go
- internal/model/user.go
- server/webdav.go
- server/webdav/file.go
Add constraints of the permission system on the admin user
Add basic permissions requirement for the WebDAV endpoint
The benefits of these modifications:
- Ensuring that the admin user is also within the scope of permission management helps to prevent accidental operations.
- Requiring two permissions for WebDAV write requests helps to achieve more refined permission management.
Frontend part AlistGo/alist-web#216
Closes #7680
> fix(permission): enhance the strictness of permissions

- cmd/common.go
- internal/bootstrap/config.go
- internal/bootstrap/data/user.go
- internal/bootstrap/patch.go
- internal/bootstrap/patch/all.go
- internal/bootstrap/patch/v3_24_0/hash_password.go
- internal/bootstrap/patch/v3_32_0/update_authn.go
- internal/bootstrap/patch/v3_41_0/grant_permission.go
- internal/conf/config.go
Add upgrade patch module, which allows for the execution of a function during the first startup after a user upgrades from an older version.
Add a patch from v3.41.0: if admin does not have Permission 0(can see hidden) - 9(webdav manage), grant them. This patch is written to help users upgrading from older version better adapt to PR #7705.
> feat(patch): upgrade patch module

- server/static/static.go
* fix #7667
* fix #6306
由于alist处理错误请求都返回200状态码，而tampermonkey会发起非webdav标准的```SUBSCRIBE```请求方法，就会导致tampermonkey一直发起请求
tampermonkey发起```SUBSCRIBE```请求方法是要监听```请求的目录```并返回```变动的文件```来实现多端实时同步，我水平不行实现不了，但基础的同步功能是可以正常工作的
> fix: static page to limit request method

- .github/workflows/release_docker.yml
- Dockerfile
- Dockerfile.ci
- entrypoint.sh
This PR migrates https://github.com/AlistGo/with_aria2 into this repo with single Dockerfile. Now we can build an image with aria2 easily by adding docker build-arg `INSTALL_ARIA2=true`.
Since four image versions need to be built in a single workflow, CI is now using the GitHub Actions Matrix to build four versions of Docker images simultaneously. Binaries only need to be built once and passed to other jobs through artifacts.
And moreover, all important variables have been moved to the top of the workflow definition file. This makes it easier for forks to change configs.
Tested with action run: https://github.com/Mmx233/alist/actions/runs/12545883543
Besides the original image with aria2, a new image named `aio` that includes both ffmpeg and aria2 has been added.
New images will be …
> feat(docker release): improve aria2 image, add aio image

- drivers/lenovonas_share/driver.go
修复 [联想个人云链接分享](https://alist.nn.ci/zh/guide/drivers/lenovonasshare.html) 驱动，stoken 过期。
示例：
> 来自联想家庭存储的分享
> https://siot-share.lenovo.com.cn/s/#/eh.h2pxSAHXYpnQ6fpu8e
> 提取码：xbax
> fix(lenovonas_share): stoken expire

- internal/model/storage.go
- internal/op/driver.go
- internal/search/build.go
Allow users to disable storage indexing.
允许用户禁用存储索引。
> feat(index): add `disable index` option for storages

- drivers/139/util.go
> fix(139): update familyGetFiles pagination logic (close #7711)

- drivers/baidu_photo/driver.go
- drivers/baidu_photo/utils.go
> fix:(baidu_photo): upload erron -6

- drivers/local/driver.go
- drivers/local/meta.go
- drivers/local/util.go
The percentage determines the point in the video (as a percentage of the total duration) at which the thumbnail will be generated.
The old implementation selects the 10th frame of the video as its thumbnail, which is typically near the beginning. This approach is not effective for distinguishing videos that have similar starting frames. Using a percentage parameter allows user control over the thumbnail generation point. Users can achieve similar behavior to the old implementation by setting the percentage to 0.
> feat(local): support both time and percent for video thumbnail

- drivers/ilanzou/util.go
https://github.com/AlistGo/alist/issues/7759 ：蓝奏优享和飞机盘无法加载出目录
1. 在调用`/app/record/file/list`接口时，返回的`list`为空
1. 通过抓包模拟，对比`alist`与蓝奏优享网页的请求，发现只有请求头部是有区别的，通过排除法，确定加上`Accept-Encoding`请求头部即可解决。
> fix(ilanzou): directory loading failure issue

- drivers/url_tree/driver.go
- drivers/url_tree/meta.go
- drivers/url_tree/types.go
- drivers/url_tree/util.go
- internal/driver/driver.go
- internal/offline_download/tool/add.go
- internal/op/fs.go
- server/handles/offline_download.go
Add a driver interface `PutURL(ctx context.Context, dstDir model.Obj, name, url string)`:
> When a user attempts to use SimpleHttp for offline downloading in a driver that implements this interface, the offline download tool will not be invoked. Instead, the `PutURL` method of the driver will be called.
Additionally implement the following interfaces for the UrlTree driver:
- `MakeDir`
- `Move`
- `Rename`
- `Copy`
- `Remove`
- `PutURL`
Closes #5166
> feat(url-tree): support url tree driver writing

- drivers/all.go
- drivers/github/driver.go
- drivers/github/meta.go
- drivers/github/types.go
- drivers/github/util.go
Add GitHub driver powered by GitHub API
每个目录下只能显示~~1,000~~ 100,000个子项，不支持操作100M以上大小的文件。
会忽略仓库内的`.gitkeep`文件，驱动全权负责该文件的管理。
没有考虑仓库里有子模块的情况，~~将来补~~ 已实现操作子模块时直接返回错误，将来不补充实现对子模块的访问支持。
~~暂时没有实现重命名、和移动，这两个功能要用别的api，暂时还没研究。~~ 已实现
~~删除目录是手动递归实现的，很耗时，但这就是官方建议的操作方法，没有更好的方法了。~~ 已改用 Tree API 实现
~~`Github.put`函数我的本意是希望文件内容每往AList发一点，AList就往GitHub发一点，同时记录进度。但我试了下好像还是变成浏览器给AList发完之后，AList才开始向GitHub发起请求了，我不知道用resty怎么实现这个功能，如果我写的确实有问题麻烦帮我改改，如果这个功能实现不了的话麻烦帮我改成调用`CacheFullInTempFile`。~~ 已实现
Document part AlistGo/docs#396
> feat(github): add github api driver

- drivers/139/meta.go
貌似移动去年底基本都迁移到新个人云了，默认老个人云可能不方便操作，另外发现之前的 group 没加，并重新调整了一下顺序
> fix(139): use `personal_new` by default

- drivers/123/driver.go
- drivers/123/upload.go
- drivers/123/util.go
- drivers/123_share/driver.go
- drivers/123_share/util.go
- drivers/139/driver.go
- drivers/139/util.go
- drivers/189pc/driver.go
- drivers/189pc/utils.go
- drivers/aliyundrive_open/driver.go
- drivers/aliyundrive_open/meta.go
- drivers/aliyundrive_open/upload.go
- drivers/aliyundrive_open/util.go
- internal/driver/driver.go
- internal/op/storage.go
支持从 `已挂载的存储` 中引用认证、令牌等。支持以下驱动
* 中国移动云盘
* 阿里云盘Open
* 天翼云盘客户端
* 123云盘分享（引用123云盘）
* 使用场景：中国移动云盘一个`Authorization`挂载多个路径、云盘类型
> feat: add `Reference` interface to driver

- internal/fs/copy.go
Previous behavior: if the driver does not support copying, `NotImplement` or `NotSupport` error will be directly responded.
Current behavior: if `op.Copy` returns `NotImplement` or `NotSupport`, the copying request will be treated as a cross-driver copying request.
> fix(copy): use Link and Put when the driver does not support copying

- drivers/alias/driver.go
- drivers/alias/meta.go
- drivers/alias/util.go
- drivers/crypt/driver.go
- drivers/github/driver.go
- drivers/halalcloud/driver.go
- drivers/mega/driver.go
- drivers/netease_music/types.go
- drivers/netease_music/upload.go
- drivers/quqi/util.go
- internal/bootstrap/config.go
- internal/conf/config.go
- internal/model/args.go
- internal/net/request.go
- internal/net/serve.go
- internal/net/util.go
- internal/offline_download/transmission/client.go
- internal/stream/stream.go
- internal/stream/util.go
- server/common/proxy.go
- server/handles/archive.go
- server/handles/down.go
- server/s3/backend.go
- server/webdav/webdav.go
* Download concurrency(下载并发)
* Download part size(下载分片大小。单位KB)
* 设置：别名驱动
本地代理
下载并发：10
下载分片大小：1024
路径：云盘的挂载路径
* 效果 ：
客户端 > alist别名驱动 ：1个连接
alist别名驱动 > 云盘 ：10 个连接并发
实际并发看云盘限制
`单线程速度慢`但`支持并发`的云盘 通过`别名`的多并发 
1. 在线看视频、下载等 可以提速
2. 从 别名 复制到 其他驱动 也可以提速
限制本地代理的最大并发，默认为64，0为不限制
> feat(alias): add `DownloadConcurrency` and `DownloadPartSize` option

- internal/archive/archives/archives.go
- internal/archive/archives/utils.go
- internal/archive/zip/zip.go
- internal/model/archive.go
- internal/op/archive.go
- internal/stream/stream.go
- pkg/utils/io.go
- server/handles/archive.go
> fix(archive): unable to preview

- server/handles/fsmanage.go
Display the existing filename in error message, in order to locate issues during batch operations.
在错误信息中显示已存在的文件名，以便在批量操作时定位问题。
> feat(fs): display the existing filename in error message

- README.md
漏了一个空格 增加以和
https://github.com/AlistGo/alist/blob/c2633dd4436a2337246979a9d866f7e408e6c2ea/README_cn.md?plain=1#L42
https://github.com/AlistGo/alist/blob/c2633dd4436a2337246979a9d866f7e408e6c2ea/README_ja.md?plain=1#L42
链接间距相同
> chore(README): formatting spacing in `README` links

- internal/conf/config.go
- internal/fs/archive.go
- internal/fs/copy.go
- internal/offline_download/tool/download.go
- internal/offline_download/tool/transfer.go
- internal/task/base.go
允许用户重试之前取消的任务，但考虑到使用习惯的问题，这一特性默认关闭，需要在 `config.json` 中启用。
不能重试上传任务。
> feat(task): allow retry canceled

- drivers/alist_v3/driver.go
- server/handles/fsup.go
在前端新增一个上传选项`Try rapid`，当选中时，前端会计算文件的 MD5、SHA1 和 SHA256，并通过`X-File-Md5`、`X-File-Sha1`、`X-File-Sha256`三个请求头传输给后端，这将避免驱动将文件缓存在服务端计算哈希，且在触发秒传时避免前端传输无用的文件流。
> perf(upload): support rapid upload on web

- drivers/s3/util.go
https://github.com/AlistGo/alist/issues/7858 ：重命名或复制文件名含有中文的文件，Signature计算错误
复制文件时，请求头部`X-Amz-Copy-Source`是源文件的路径，计算`Signature`时会用到它；华为云是按转义后的`CopySource`计算`Signature`，而`alist`没有做转义，导致签名不一致报错
其实`AWS`官方也是要求做转义的，不过经过测试腾讯云对象存储`COS`对两种情况都做了兼容，所以没有报错
对CopySource增加转义操作
华为云-重命名含中文的文件 --- OK
华为云-重命名含中文的目录 --- OK
华为云-重命名英文的文件    --- OK
腾讯云-重命名含中文的文件 --- OK
腾讯云-重命名英文的文件    --- OK
> fix(s3): escape CopySource request header when copying files

- server/handles/fsbatch.go
Add `overwrite` option for recursive move to preventing unintentional overwriting.
为聚合移动增加『覆盖已有文件』选项以防止意外的数据丢失。
close: https://github.com/AlistGo/alist/issues/7382
close: https://github.com/AlistGo/alist/issues/7719
> feat(recursive-move): add `overwrite` option to preventing unintentional overwriting

- drivers/all.go
- drivers/github_releases/driver.go
- drivers/github_releases/meta.go
- drivers/github_releases/types.go
- drivers/github_releases/util.go
resolve #7842 
添加对 GitHub Releases 的支持，将多个仓库的最新版 Releases 挂载到 AList，方便不了解 GitHub 的用户下载。
同时可选是否获取仓库根目录下的 `*.md` 和 `LICENSE` 文件。
配置项：
| 配置项 | 类型 | 是否必填 | 描述 |
| ---- | ---- | ---- | ---- |
| RepoStructure | text | 是 | 仓库结构 |
| ShowReadme | bool | 是 | 是否显示 `*.md` 和 `LICENSE` 文件 |
| Token | string | 否 | GitHub 访问令牌，用于私有仓库 和 避免访问速率限制 |
| ShowAllVersion | bool | 是 | 开启后以子目录的形式显示所有版本 |
RepoStructure 使用类似地址树的方式，但不使用缩进表示目录，支持多级路径。
效果示例（不显示所有版本）：
效果示例（显示所有版本）：
补充说明：
+ 目录大小由子目录相加得到，未计算 `*.md` 和 `LICENSE` 文件的大小。
+ 使用 `map` 缓存接口响应，减少访问速率限制的影响。
> feat(github_releases): add support for github_releases driver

- drivers/all.go
- drivers/misskey/driver.go
- drivers/misskey/meta.go
- drivers/misskey/types.go
- drivers/misskey/util.go
| 参数名 | 类型   | 必填 | 说明                                      |
| ------ | ------ | ---- | ----------------------------------------- |
| endpoint   | string | 是   | Misskey实例端点 |
| token  | string | 是   | Misskey API访问令牌，需要write:drive和read:drive权限     |
目前驱动所有功能实现完毕，并通过实例测试，由于Misskey本身没有复制文件的功能，因此复制功能是Misskey实例从自己下载文件到新位置实现
> feat(misskey): add misskey driver

- drivers/febbox/util.go
https://github.com/AlistGo/alist/issues/7889
`/oauth`接口返回的`data`在异常情况下会为空，导致越界发生`panic`
增加判断`data`切片长度
> fix(febbox): panic due to slice out of range

- drivers/139/driver.go
本更新回滚了 #7850 中的部分修改
可能相关的 issue： #7784 
都说是移动 2024 年年底把所有账户都转到了新个人云接口，但我这里按 F12 却仍然只能找到旧的 `getDisk` ，而且**使用新个人云接口上传的文件在官方网页端和客户端里根本看不到**，而且也缺失了很多文件。
无奈只能换回老个人云，结果猛报 `failed get objs: failed to list objs: 用户不存在` ，读代码一看：怎么把 `getAccount` 的逻辑注释了。
> fix(139): restore the `Account` handling, partially reverts #7850

- drivers/lenovonas_share/types.go
> fix(lenovonas_share): dir size

- server/handles/fsread.go
fix:[7932](https://github.com/AlistGo/alist/issues/7932)，当使用alias驱动，302获取rawURL错误。
> fix: missing args when using alias driver

- drivers/github_releases/driver.go
- drivers/github_releases/meta.go
- drivers/github_releases/models.go
- drivers/github_releases/types.go
- drivers/github_releases/util.go
| 配置项 | 类型 | 是否必填 | 描述 | 示例 |
| ---- | ---- | ---- | ---- | ---- |
| RepoStructure | text | 是 | 仓库结构 | alist-org/alist |
| ShowReadme | bool | 是 | 是否显示 `*.md` 和 `LICENSE` 文件 |  |
| Token | string | 否 | GitHub 访问令牌，用于私有仓库 和 避免访问速率限制 |  |
| ShowAllVersion | bool | 是 | 开启后以子目录的形式显示所有版本 |  |
| GitHubProxy | string | 否 | 使用 gh-proxy | https://ghproxy.net/github.com |
之前偷懒使用了 `jsoniter.Get` 动态访问 JSON 字段。我写统计所有版本的总文件大小时，发现耗时过久。
只统计 latest 总大小时耗时不明显，所以没注意到。(T＿T)
改用 `json.Unmarshal` 解析到静态字段，再统计总大小，似乎能提升速度。
因此，本次 pr 也支持了显示所有版本时，统计目录大小。
之前，开启 `显示所有版本` 和 `显示 README` 后：
```
alist/
├── v3.41.0/
│   ├── alist-linux-amd64.tar.gz
│   ├── alist-linux-amd64.tar.gz
│   ├── LICENSE
│   └── README.md
├── v3.40.0/
│   ├── alist-linux-amd64.tar.gz
│   ├── alist-linux-amd64.tar.gz
│   ├── LICENSE
│   └── …
```
> feat(github_releases): support dir size for show all version

- .github/workflows/beta_release.yml
- .github/workflows/build.yml
- build.sh
- cmd/version.go
- internal/conf/var.go
- Remove the `GoVersion` variable
- Remove overriding `GoVersion` by ldflags in `build.sh` and ci workflows.
- Get go version, OS and arch from the constants in the std `runtime` package instead of compile time.
> refactor(cmd): use std `runtime` package to get go version info

- server/common/common.go
- server/handles/const.go
- server/handles/fsbatch.go
Advanced conflict policy for preventing unintentional overwriting:
增加冲突策略选项以防止意外的数据丢失。
- Cancel if file exists
- 如果文件已存在，则取消操作
- Overwrite existing files
- 覆盖已存在文件
- Skip existing files
- 跳过已存在文件
> feat(recursive-move): Advanced conflict policy for preventing unintentional overwriting

- internal/bootstrap/data/setting.go
Fix: https://github.com/AlistGo/alist/issues/7772#issuecomment-2630259396
`.url` 格式没有默认添加到代理类型中，`/p/` 会返回 403
GET http://127.0.0.1:5244/p/onedrive/jump.url?alist_ts=1738570002208
```json
{"code":403,"message":"proxy not allowed","data":null}
```
前端：https://github.com/AlistGo/alist-web/pull/248
> feat(bootstrap): add `.url` to proxy types

- drivers/ilanzou/driver.go
- drivers/ilanzou/meta.go
- drivers/ilanzou/util.go
resolve #7966, resolve #7581, resolve #7759, resolve #7534
添加 `X-Forwarded-For` 请求头（可选），来避免阿里云 IP 无法获取文件列表
[详见 issue 中讨论](https://github.com/AlistGo/alist/issues/7759#issuecomment-2583503228)
ilanzou（蓝奏云优享版）和小飞机网盘使用相同的驱动。
> fix(ilanzou): add header `X-Forwarded-For` to solve IP ban

- drivers/github/driver.go
- drivers/github/meta.go
GitHub API 驱动支持 GitHub 专用代理。
考虑到 GitHub Releases 驱动已经实现这一特性，该 PR 会关闭提出这一需求的 issue。
Close #7963
需要注意的是，该驱动返回的下载 URL 是 raw.githubusercontent.com 域名下的，因此填写代理参数时与 GitHub Releases 驱动也有所不同，比如要将`https://gh-proxy.com/github.com`改为`https://gh-proxy.com/raw.githubusercontent.com`。
> feat(github): support github proxy

- internal/bootstrap/data/setting.go
- internal/conf/const.go
支持打开压缩文件时优先展示下载而不是预览，在`设置->预览`中设置。
Front-end part: AlistGo/alist-web#252
> feat(archive): support deprioritize previewing

- drivers/alias/util.go
- drivers/crypt/driver.go
- drivers/quark_uc/util.go
- drivers/quqi/util.go
- internal/net/request.go
- internal/net/serve.go
- internal/net/util.go
- internal/stream/stream.go
- internal/stream/util.go
- pkg/utils/io.go
- server/common/proxy.go
- server/s3/backend.go
- server/webdav/prop.go
- server/webdav/webdav.go
* 让使用stream.GetRangeReadCloserFromLink发起请求的行为跟`本地代理`的一致，例如 Crypt 驱动
*  Close #8008 
* 添加Etag响应头的作用之一：在浏览器重启之后 继续播放视频时 加载变快
> refactor(net): pass request header

- drivers/baidu_netdisk/driver.go
- drivers/baidu_netdisk/meta.go
- drivers/baidu_netdisk/util.go
两个讨论点：
`MaxSliceNum`使用文档里的`1024`还是实测的`2000`.
`SliceStep`使用`1 MiB`还是`4 MiB`.
是否需要更新前端/翻译？
我会负责更新文档
> feat(baidu_netdisk): support dynamical slice size for low bandwith upload case

- drivers/cloudreve/driver.go
使用毫秒时间戳，修复上传文件时间为类似 1970-01-21 04:14:28 的问题
> fix(cloudreve): use milliseconds timestamp in last_modified

- drivers/cloudreve/util.go
- drivers/onedrive/util.go
- drivers/onedrive_app/util.go
显式设置 req.ContentLength，防止 http 库自动启用 chunked 传输，导致无法上传
Fix: #8043
> fix(onedrive): set req.ContentLength

- drivers/crypt/driver.go
- server/common/proxy.go
我的锅，没想到`github.com/rclone/rclone/backend/crypt`这个包会调用Close
* Close #8119
> fix(crypt): premature close of MFile

- pkg/utils/hash.go
- server/webdav/prop.go
实现 #7472 的功能。
相比该 issue 中提出的 `al:checksums`，这个 PR 实现的是 ownCloud 的 `oc:checksums`，这样可以兼容现有支持该属性的软件（如 rclone）。
Closes #7472
> feat(webdav): support `oc:checksums`

- drivers/s3/util.go
该Bug主要涉及到Issue #8001，Error可复现，表现为S3存储无法重命名文件
后端使用Master分支，Commit 370a6c15，启动后进行一次重命名，在页面上会报错
同时查看日志有：
```bash
ERRO[2025-03-04 22:21:28] /alist/internal/fs/fs.go:84 github.com/alist-org/alist/v3/internal/fs.Rename() failed rename /R2/c.app to e.app: InvalidArgument: copy source bucket name
status code: 400, request id: , host id: 
github.com/alist-org/alist/v3/internal/op.Rename
/Users/xiejiangzhao/alist/internal/op/fs.go:428
github.com/alist-org/alist/v3/internal/fs.rename
/Users/xiejiangzhao/alist/internal/fs/other.go:40
github.com/alist-org/alist/v3/internal/fs.Rename
/Users/xiejiangzhao/alist/internal/fs/fs.go:82
github.com/alist-org/alist/v3/server/handles.FsRename
/Users/xiejiangzhao/alist/server/handles/fsmanage.go:188
github.com/gin-gonic/gin.(*Context).Next …
```
> fix(s3): incorrectly added slash before the Bucket name

- drivers/quqi/driver.go
- drivers/quqi/util.go
- drivers/vtencent/util.go
- internal/net/request.go
- pkg/utils/path.go
- server/common/proxy.go
- server/handles/down.go
> refactor: FilterReadMeScripts

- internal/op/sshkey.go
- server/handles/sshkey.go
- server/sftp.go
在数据库中存储原始 SSH 公钥，以解决 Postgre 无法存储 Marshal 后的公钥的问题。
Close #8186
> fix(sftp-server): postgre cannot store control characters

- drivers/189pc/utils.go
- drivers/baidu_netdisk/driver.go
- drivers/baidu_photo/driver.go
- drivers/mopan/driver.go
#7948 没有考虑到分片上传失败会重新执行上传函数，导致信号量因被获取一次释放多次而 panic。
现将获取信号量放到线程内部，不好的点是上传过程中可能会创建大量空等待的线程，但总比 panic 要好。errgroup 的 onRetry 回调函数看了看源代码感觉不是很好用。
Fix #8180
> fix(traffic): duplicate semaphore release when uploading

- drivers/alias/driver.go
- drivers/alias/meta.go
- drivers/alias/util.go
- internal/fs/fs.go
- internal/offline_download/tool/add.go
- internal/op/archive.go
别名驱动支持所有不冲突路径的写入操作。
举例说明：假设 A，B 两驱动的内容如下：
```
A
└ dir1
├ file1
├ file2
└ dir2
B
├ dir1
│ └ file1
└ dir3
```
现将它们引入到一个别名驱动内，**打开别名驱动的“可写”和“同名保护”两个选项**，则
- `/dir1`下不可以上传文件、创建文件夹，也不能作为驱动内复制、移动、解压操作的目标文件夹（以下称“写入操作”），因为 A、B 两驱动都有路径`/dir1`，不能确定在此处进行写入操作时应该写入到哪个驱动。
- `/`下不可以进行写入操作，原因同上， A、B 两驱动都有根目录`/`。
- `/dir1/dir2`下可以进行写入操作，因为只有驱动 A 有文件夹`dir2`，在此处写入不存在歧义，如果手动在驱动 B 的文件夹`dir1`下创建文件夹`dir2`，则`/dir1/dir2`会重新变得不可写入。
- `/dir3`下可以进行写入操作，原因同上。
- `/dir1/file1`不可以作为驱动内复制、移动、解压操作的源文件，也不可以删除或重命名，因为不能确定进行操作的文件来自哪个驱动。
- `/dir1`不可以被复制、移动、解压、删除、重命名，原因同上。
- `/dir1/file2`可以被复制、移动、解压、删除、重命名（请注意，此处对删除和重命名操作的支持并不来源于这个 PR，而是来源于 #6478），因为对其操作是无歧义的。
对于不展开用法，例如如下配置：
```
a:驱动1路径
a:驱动2路径
b:驱动3路径
```
则
- `/`目录不可写
- `/a`目录不可写，原因与展开用法的`/`不可写一致
- `/b`目录可以作为驱动内复制、移动、解压操作的目标文件夹，可以上传子文件和创建子文件夹，但不可以被复制、移动、删除、重命名 …
> feat(alias): support writing to non-ambiguous paths

- internal/net/serve.go
- internal/stream/util.go
- server/common/proxy.go
* 恢复部分修改 https://github.com/AlistGo/alist/pull/8031/commits/5be50e77d9ad8d67e343aa7e9380bcdd2506ae8f
stream.GetRangeReadCloserFromLink只在内部使用，传递请求头好像不是个好选择😢
* https://github.com/AlistGo/alist/issues/8119#issuecomment-2765817711
> revert "refactor(net): pass request header"

- drivers/139/driver.go
- drivers/139/meta.go
- drivers/139/types.go
> feat(139): add option ReportRealSize

- README.md
- drivers/all.go
- drivers/azure_blob/driver.go
- drivers/azure_blob/meta.go
- drivers/azure_blob/types.go
- drivers/azure_blob/util.go
- go.mod
- go.sum
Introduce a new driver for Azure Blob storage, enabling integration with Azure's storage services. 
This implementation **based on azure blob Golang SDK**, includes methods for file operations such as upload, delete, and copy, along with batch processing capabilities
- 使用共享密钥身份验证初始化连接
- 列出目录和文件
- 生成临时 SAS URL 进行文件访问
- 创建目录
- 移动和重命名文件/文件夹
- 复制文件/文件夹
- 删除文件/文件夹
- 上传文件并支持进度跟踪
* 不能自动创建container，(alist 功能不影响)
* 大文件重命名和移动操作效率很低 (blob 没有rename能力，所以是复制删除实现，datalake gen2 版的存储和API支持rename，但是认证似乎比较复杂)
* 文件夹是虚拟目录实现
PS:
Golang 没怎么写过，代码大部分是Copilot写的,请review详细点
> feat(driver): add Azure Blob Storage driver

- drivers/baidu_netdisk/driver.go
- drivers/baidu_netdisk/meta.go
- drivers/baidu_netdisk/types.go
- drivers/baidu_netdisk/util.go
为 百度网盘驱动添加了新的下载接口 `crack_video` ，仅能获取视频文件的地址，目前测试下来，无vip可原画满速下载，仍需要ua
同时还增加了 `OnlyListVideoFile` 选项，是否仅展示视频文件(包括文件夹)
> fix(baidu_netdisk): add another video crack api

- drivers/ipfs_api/driver.go
- drivers/ipfs_api/meta.go
进行了进一步的测试
发现了由于路径拼接导致的中文和带符号路径无法正常使用的问题
使用更加规范的路径拼接，修复了有中文或符号的路径无法正常访问的问题
提高性能
提高性能
允许覆写文件
使用parent参数，例如允许直接使用/aa/bb/m.md同时创建目录和文件
> fix(ipfs): fix problems

- internal/net/serve.go
- server/common/proxy.go
- server/handles/down.go
- server/webdav/webdav.go
> fix(net): unexpected write

- internal/op/fs.go
当执行 Rename 时，并启用 Overwrite existing files 选项时，由于重命名的目标没有从缓存中被删除，导致目录缓存中存在两个同名文件，因此列目录时(可能)看到的依然是旧文件。
本 PR 在更新缓存前从缓存中删除了旧的目标文件，以确保缓存正确性。
BTW，对于未勾选 Overwrite existing files 选项的情形，由于目标文件不存在，因而不会触发删除操作。
> fix(fs): remove old target object from cache before updating

- drivers/doubao/driver.go
- drivers/doubao/meta.go
- drivers/doubao/types.go
- drivers/doubao/util.go
为 豆包驱动 添加了上传功能，默认三线程。同时修复了下载接口的参数传值。
> feat(doubao): support upload

- drivers/url_tree/driver.go
- internal/op/fs.go
- internal/op/path.go
#7779 的拓展，添加了接口Put，支持直接在网页中通过新建文件的方式添加链接到URL-TREE。
Closes #8303
> feat(url-tree): implement the Put interface to support adding links directly to the UrlTree on the web side

- drivers/aliyundrive_open/driver.go
- drivers/aliyundrive_open/util.go
建议来自 https://github.com/AlistGo/alist/issues/7962#issuecomment-2745873325
本次提交解决了阿里云盘开放接口驱动中的几个问题：
1. 通过实现新的removeDuplicateFiles方法清理操作后的重复文件，修复文件重复问题
2. 将移动操作的check_name_mode从"refuse"改为"ignore"，允许在目标目录存在同名文件时进行移动
3. 设置复制操作在成功复制后处理重复文件
4. 改进所有文件操作(移动、重命名、上传、创建目录)的路径处理，正确维护对象的完整路径
5. 实现GetRoot接口，使根对象能够正确初始化并设置正确路径
6. 在列表操作中添加适当的路径管理，确保对象拥有正确的路径
7. 修复错误情况下的路径处理，并改进失败日志记录
这些更改确保了在存在重名文件的情况下，文件操作能够正确工作，同时保持数据完整性并防止重复文件在阿里云盘中累积。
> fix(aliyundrive_open): resolve file duplication issues and improve path handling

- drivers/all.go
- drivers/doubao_share/driver.go
- drivers/doubao_share/meta.go
- drivers/doubao_share/types.go
- drivers/doubao_share/util.go
增加了 豆包分享链接的驱动
配置项说明
`Root folder path` 请保持默认的`/`
`Cookie` 字段，请自行打开[豆包云盘](https://www.doubao.com/chat/drive/)，获取其`Cookie`中的关于`ttwid`部分，
例如：`ttwid=xxxx;`
`Share ids`字段，填写需要挂载的分享链接或`ID`，可自定义路径，格式要求如下：`分享链接或ID` + `|` + `自定义路径(可选)`
例如：有一个`分享链接：https://www.doubao.com/drive/s/aabbccddeeffgghh`需要挂载，其`ID`为`/s/后面的`：`aabbccddeeffgghh`
> 有下面几种填写方式
> - `https://www.doubao.com/drive/s/aabbccddeeffgghh`：分享内容直接展示在根目录
> `aabbccddeeffgghh`：分享内容直接展示在根目录——使用分享链接或者分享的ID都可以
> - `https://www.doubao.com/drive/s/aabbccddeeffgghh|测试目录`：根目录 -> 测试目录 -> 分享内容
> - `https://www.doubao.com/drive/s/aabbccddeeffgghh|测试目录/1/2`：根目录 -> 测试目录 -> 1 -> 2 -> 分享内容
`多分享链接或ID` 的情况：
> - `https://www.doubao.com/drive/s/aabbccddeeffgghh|测试目录1`
> `https://www.doubao.com/drive/s/bbaaccddeeffgghh|测试目录2`
> 效果：
> ```
>	      -- 测试目录1 -> 分享内容 …
```
> feat(doubao_share): support doubao_share link

- drivers/azure_blob/meta.go
implement GetRootId interface in Addition struct to fix failed get dir:
now
> fix(azure_blob): implement GetRootId interface in Addition struct

- Dockerfile
- Dockerfile.ci
Using `COPY --chmod=755` instead of `chmod +x` prevents Docker from creating duplicate layers for the binary file, which will resolve the abnormal increase in image space usage since v3.42.0.  
Although the issue only occurs in CI, I also update the local Dockerfile for consistency.
Close: #8388
> fix(docker release): avoid duplicate occupation in docker image

- drivers/mega/driver.go
Close: #8344
Mega 支持一个文件夹下有多个同名文件（duplicate names），不同版本以日期区分。
AList mega driver 的 `Link()` 方法会返回多个「同名」文件，但最终 AList 只会响应第一个版本（最旧的）进行列出/下载。这就导致无论你上传了多少遍，读取到的永远是最旧的版本。
PR 是对 `Link()` 里的同名文件进行了过滤，只保留最新版本，这样 CRUD 都能保持一致
上图，首先是 Mega 官方
修复前（Test in v3.42）
修复后（PR）
> fix(mega): use newest file for same filename

- entrypoint.sh
Change from `#!/bin/bash` to `#!/bin/sh`. A wrong shebang may cause images built on some platforms, such as Docker Desktop, to throw an error: `exec /entrypoint.sh: no such file or directory`.
Example image: `mmx233/alist:joint-20250420`
The `/entrypoint.sh` file does exist, but the error will occurs because of the shebang.
> fix(docker_release): shebang of entrypoint.sh

- server/router.go
API router of authn login should not contain auth middleware. Currently, the API will throw an error only when there is an invalid token during login; If the token is empty, the request will succeed and the request will be granted a Guest identity, regardless of whether the Guest is disabled or not.
This PR is prerequisite for https://github.com/AlistGo/alist-web/pull/274
Image for test: `mmx233/alist:frontend-20250420`
To meet testing requirements, this image includes changes from both https://github.com/AlistGo/alist-web/pull/274 and https://github.com/AlistGo/alist-web/pull/273.
> fix(authn): remove auth middleware for webauthn login api

- drivers/netease_music/types.go
更改 `ListResp.Size`、`ListResp.MaxSize` 的类型为 `int64`，避免 JSON 反序列化错误。
Close: https://github.com/AlistGo/alist/issues/8406
> fix(netease_music): change ListResp size fields from string to int64

- drivers/doubao/driver.go
- drivers/doubao/meta.go
- drivers/doubao/types.go
增加 `get_download_info` 这个 API，目前网页端默认使用，返回的链接带有文件名参数，不会出现文件名被编码的问题，支持获取视频文件的下载链接，获取到图片的下载地址也不会被压缩（不包括 PNG）。
Note: 文件名参数：`?attname=`
> feat(doubao): add get_download_info API and download_api option

- server/handles/auth.go
Currently, if the guest account is enabled, anyone can modify the guest user's username and password through the `/api/me/update` API endpoint without any authentication (something that even admins cannot do through the user management interface). While testing has not revealed any severe security issues, I believe no one wants to see the GUEST username changed to "You are cute"  (⁄ ⁄•⁄ω⁄•⁄ ⁄) .
Added a check for Guest users in the `UpdateCurrent` function. When a Guest user attempts to modify their profile information, the system now returns a 403 error and blocks the operation. This is consistent with restrictions applied to Guest users in other functions (such as `Generate2FA`).
This small change ensures your GUEST user won't suddenly become unexpectedly charming without your …
> fix: prevent guest user from updating profile

- drivers/all.go
- drivers/cloudreve/driver.go
- drivers/cloudreve/util.go
- drivers/cloudreve_v4/driver.go
- drivers/cloudreve_v4/meta.go
- drivers/cloudreve_v4/types.go
- drivers/cloudreve_v4/util.go
- drivers/onedrive/util.go
- drivers/onedrive_app/util.go
适配 Cloudreve V4，其API部分发生改动较大，特独立成一个存储。
Close: https://github.com/AlistGo/alist/issues/8328
Close: https://github.com/AlistGo/alist/issues/8467
此外，本 PR 还进行了：
- 对之前的 Cloudreve、OneDrive、OneDrive APP 驱动（使用类似的上传方法）加入了分片上传失败自动重试机制，提高上传成功率。
- 对 Cloudreve 增加了 https://github.com/AlistGo/alist/pull/7805 引入的 ref 支持。
文档：https://github.com/AlistGo/docs/pull/433
Cloudreve V4 支持使用 Access Token 和 Refresh Token 进行鉴权，这意味着挂载鉴权方式分为：
1. 账号+密码：会自动使用登录接口获取 Access Token 和 Refresh Token，存在验证码问题
2. 仅 Refresh Token：会自动使用刷新接口续期 Access Token 和 Refresh Token，参数可从浏览器请求或者 Local Storage 中找到
3. 仅 Access Token：能够临时使用，但会过期，且无法续期
4. 无：匿名用户，适用于公开分享
5. 备注填写 `ref:/{挂载路径}`：从 `已挂载的存储` 中引用认证、令牌等，同一个 Token 多个网盘使用
Cloudreve V4 采用自定义 URI 作为路径。可从网页链接的 `?path=` 中获取。
默认为 `cloudreve://my/`，列出用户文件。 …
> feat(cloudreve_v4): add Cloudreve V4 driver

- internal/bootstrap/log.go
fix: #9237 
- Adjust log formatter to disable colors when NO_COLOR or ALIST_NO_COLOR environment variables are set.
- Reorganize formatter settings for better readability.
> feat(log): enhance log formatter to respect NO_COLOR env variable

- go.mod
- go.sum
- Upgrade `github.com/SheltonZhu/115driver` to v1.1.2 in `go.mod`
- Modify `replace` to point to `github.com/okatu-loli/115driver v1.1.2`
- Remove old version checksum from `go.sum` and add new version checksum
> chore(deps): Update 115driver dependency to v1.1.2

- drivers/local/driver.go
- drivers/local/util.go
> refactor(driver): Refactored directory link check logic
