AlistGo/alist

drivers/alidrive/driver.go, utils/md5.go
=> 增加阿里云秒传 #652

drivers/189pc/189.go, drivers/189pc/driver.go, drivers/189pc/type.go, drivers/189pc/util.go, drivers/all.go
=> 修复天翼云盘大文件 #683  支持天翼家庭云 #612

drivers/189pc/189.go, drivers/189pc/driver.go, drivers/xunlei/driver.go
正好把前面的问题改一下
还有就是我发现如果文件名带#的话浏览器会识别成锚点导致无法访问
=> 修复部分代码，修复迅雷翻页

drivers/xunlei/driver.go, drivers/xunlei/util.go, drivers/xunlei/xunlei.go
忘记判断文件存在时的操作了...
https://github.com/Xhofe/alist/blob/b21801d5057c705ffffefbdfa94e09654953df49/server/webdav/webdav.go#L291
这有问题，没有处理错误会有空指针
=> 修复迅雷上传报错 #749

README.md, README_cn.md, bootstrap/account.go, drivers/alidrive/alidrive.go, drivers/alidrive/driver.go, drivers/operate/operate.go, drivers/quark/driver.go, drivers/quark/quark.go, drivers/s3/driver.go, drivers/s3/s3.go, drivers/s3/util.go, drivers/xunlei/xunlei.go, model/account.go, model/setting.go, server/common/common.go, server/common/files.go, server/controllers/account.go, server/controllers/file/folder.go, server/controllers/path.go, server/webdav/file.go, utils/cookie/cookie.go
- fix quark cookie expired
- fix aliyundrive's response of move and copy
- virtual path
closes #830 #856 #828
=> fix quark cookie, virtual path

server/common/common.go, server/webdav/file.go
=> fix: some issues of webdav due to virtual path

drivers/baidu/baidu.go, drivers/baidu/driver.go, drivers/baidu/types.go
感谢@[alizyw](https://github.com/alizyw)提供的百度网盘api接口(太快了会不会封号？？？)
=> 修复百度网盘API文件大于20M问题

drivers/xunlei/driver.go, drivers/xunlei/types.go, drivers/xunlei/util.go, drivers/xunlei/xunlei.go, model/account.go
1.修复迅雷下载限速问题
2.允许自定义客户端信息
3.出现验证码后可手动访问错误信息中的网站，手动验证后复制captcha_token填入后端verified captcha token中保存（迅雷手机端出现验证码概率高）
=> fix(xunlei):download link speed limit

drivers/baiduphoto/driver.go, drivers/baiduphoto/types.go, drivers/xunlei/xunlei.go
fix: 
- xunlei login (close #1053)
- baidu.photo path error for windows
=> fix baidu.photo and xunlei

drivers/xunlei/driver.go, drivers/xunlei/xunlei.go, go.mod, go.sum
1.根据群友反馈，部分手机或邮箱无法获取到验证码（无法测试，不确定是否修复）
2.翻页逻辑问题，会死循环
3.保存验证码逻辑问题
4.参考pikpak，优化迅雷的上传方式（迅雷hash无法用于秒传）
=> 修复迅雷一些已知问题

drivers/123/driver.go, drivers/189pc/driver.go, drivers/alidrive/driver.go, drivers/xunlei/driver.go
1.忘记defer 是后声明先执行了，导致缓存未删除
2.增加123流式上传选择，测试功能不建议使用，我测试了50GIB数据也没出问题，不知道后面会不会出问题
=> 增加123流式上传选择

drivers/all.go, drivers/chaoxing/chaoxing.go, drivers/chaoxing/driver.go, drivers/chaoxing/types.go, drivers/chaoxing/util.go, go.mod, go.sum
根据超星网盘的实际情况初步实现了driver 接口，后续会实现一些文件操作（已知网盘不支持复制，删除函数较危险，怕翻车，放到最后实现）
=> 新增对超星网盘的支持

drivers/chaoxing/driver.go, drivers/chaoxing/util.go
增强了超星网盘的功能，现在还差上传没有实现，等我弄明白现有的代码再说
=> 实现文件移动、删除、重命名等功能，增加提示信息

bootstrap/auth.go, bootstrap/setting.go, conf/var.go
=> fix: modify the frontend type of the certificate

cmd/server.go
暂时没有找到如何从外部包调用函数启动的方式，这里增加一个入口
=> 增加一个外部启动server的函数。

drivers/google_photo/driver.go, drivers/google_photo/meta.go, drivers/google_photo/types.go, drivers/google_photo/util.go
=> feat(google_photo): Add categories in root, add album support.

internal/bootstrap/data/user.go
允许通过环境变量`ALIST_ADMIN_PASSWORD `设置初始化管理员密码
Signed-off-by: ysicing <i@ysicing.me>
=> feat(user): add init user default password

drivers/alist_v3/driver.go, drivers/alist_v3/meta.go, drivers/alist_v3/types.go, drivers/alist_v3/util.go, drivers/all.go, server/common/common.go, server/common/resp.go
Not sure how to implement user login.
=> feat: add alist v3 driver (close #1833)

drivers/115/meta.go, drivers/115/util.go, go.mod, go.sum
=> feat(115): add qrcode login

drivers/115/util.go, go.mod, go.sum
* fix duplicate cookies in client.List func
* rm useless cookies when init
=> fix(115): update 115 driver lib to fix some bugs

internal/aria2/monitor.go
fix #1856, handle aria2 directories
=> fix(aria2) #1856, solve directory issue

.github/ISSUE_TEMPLATE/bug_report.yml
=> ISSUES 模板无法上传截图

cmd/common.go, internal/db/searchnode.go, internal/model/search.go
As we do not use s% on name column, index there does not work
=> feat: remove index on `SearchNode.Name`

drivers/all.go, drivers/pikpak_share/driver.go, drivers/pikpak_share/meta.go, drivers/pikpak_share/types.go, drivers/pikpak_share/util.go
=> feat: add pikpak share driver (#2728)

cmd/admin.go, cmd/cancel2FA.go, cmd/lang.go, cmd/restart.go, cmd/root.go, cmd/server.go, cmd/start.go, cmd/stop.go, cmd/version.go
so that it can be used from another go package
=> feat: export all cmd

Dockerfile, entrypoint.sh
Fix https://github.com/alist-org/alist/issues/2525
=> Add PUID, PGID, Umask settings to Docker image

internal/db/searchnode.go
=> fix(mysql): change mysql against mode(#2903)

drivers/lanzou/driver.go, drivers/lanzou/help.go, drivers/lanzou/meta.go, drivers/lanzou/types.go, drivers/lanzou/util.go
本来想直接就返回正确的文件信息的,但奈何蓝奏云api太脆弱只能在获取链接的时候修改信息ψ(｀∇´)ψ.
=> fix(lanzou):webdav unable to download and upload. (close #2700)

drivers/uss/driver.go, drivers/uss/meta.go
1.修复文件过多而导致的列表读取无响应的问题
2.修复文件下载url协议头的判断错误
3.整合CustomHost和Endpoint设置项，统一使用Endpoint表示又拍云存储加速域名
=> fix: resolve USS driver problem

drivers/139/driver.go, drivers/139/util.go, internal/driver/driver.go
fix: The file size is exceeded and cannot be uploaded
fix: File name has special characters, signature fails
improve: optimize memory usage
Signed-off-by: aimuz <mr.imuz@gmail.com>
=> fix: yun.139 upload fail

README.md, drivers/all.go, drivers/seafile/driver.go, drivers/seafile/meta.go, drivers/seafile/types.go, drivers/seafile/util.go
=> feat: add Seafile driver

drivers/lanzou/driver.go
Solve the problem that files cannot be uploaded to the specified directory
=> fix(Lanzou):files cannot be uploaded to the specified directory

internal/fs/util.go
=> feat(fs): create symbolic link instead of copy local files

drivers/aliyundrive/driver.go, drivers/aliyundrive/help.go, drivers/aliyundrive/meta.go, drivers/aliyundrive/util.go, go.mod, go.sum, pkg/utils/hash.go
临时修复，部分错误判断逻辑未完善，但不妨碍使用（运气太差除外）。
=> fix(aliyundriver):x-drvice-id error code

internal/op/path.go
more info pls refer to: https://segmentfault.com/a/1190000043031147
=> refactor: friendly tip for initial logging in

internal/bootstrap/data/setting.go
https://github.com/alist-org/alist/pull/3649#issuecomment-1450236108
=> Feat: show sso settings at a more reasonable sort

drivers/smb/driver.go, drivers/smb/util.go
=> fix: smb drive lastConnTime data race

server/handles/fsmanage.go, server/router.go
提供文件聚合接口与文件正则重命名接口：
1. 文件聚合接口：支持将给定文件夹及其子文件夹下的文件移动到目标文件夹。
2. 文件正则重命名接口：支持将文件夹下所有文件按给定正则表达式重命名。
=> feature：提供文件聚合接口与文件正则重命名接口；

drivers/aliyundrive/driver.go
Allow cancelling upload during checksum for very large files
=> feat(aliyundrive): make checksum cancellable

pkg/task/manager.go, server/handles/task.go
#3798 
新增仅清除成功记录和出错重试选项，点了重试手动点下刷新。（solidjs不太熟悉欢迎继续PR）
重试功能我测试能成功，不过各家网盘差异巨大，如有bug建议删除任务重新复制。
尚未增加分页查看以及全部重试选项，是否有必要欢迎进一步反馈
=> feat(task): add clear succeeded and retry

drivers/trainbit/driver.go, drivers/trainbit/util.go
=> fix(Trainbit): remove unnecessary operation

drivers/115/driver.go
=> fix(115): fix download bug (close #3926)

server/handles/fsmanage.go, server/router.go
* feat: add empty folder clear api
=> feat(drivers): empty folder clear API

server/handles/fsmanage.go
- fix the recursive subdirectory moving bug
=> fix(drivers): the recursive subdirectory moving bug.

internal/qbittorrent/client.go
#4199
qbittorrent AddFromLink set autoTMM to false
=> fix(qbittorrent): set autoTMM

server/handles/ssologin.go
Fix: https://github.com/alist-org/alist/issues/4266
https://user-images.githubusercontent.com/3787410/235297865-5b77094f-23ad-4b5f-bce3-5f2249ced716.mp4
=> fix: fix cannot connect to Casdoor SSO bug

drivers/cloudreve/driver.go, drivers/cloudreve/meta.go, drivers/cloudreve/util.go
Feat(drivers): Support set cookie for Cloudreve #4324
As with my Issues, some of the Cloudreve sites have reCaptcha enabled, and this PR will support users setting cookies directly for mounting
=> Feat(drivers): Support set cookie for Cloudreve (#4324)

drivers/baidu_photo/help.go, drivers/baidu_photo/utils.go
fix:https://github.com/alist-org/alist/issues/4351
=> fix(baidu_photo):Change folder name length

drivers/115/util.go, drivers/base/client.go, drivers/lanzou/driver.go, drivers/lanzou/util.go, drivers/quark/driver.go, drivers/trainbit/driver.go, drivers/trainbit/util.go, drivers/webdav/odrvcookie/fetch.go, internal/bootstrap/config.go, internal/fs/util.go, server/common/proxy.go
https://github.com/alist-org/alist/issues/4355
我检出修改后的测试，发现没改干净，大量的证书验证问题导致无法通过。
所以我重新组织后改了一遍，亲测可用。
=> BUG:tls_insecure_skip_verify配置未生效 #4355

drivers/189pc/driver.go, drivers/189pc/help.go, drivers/189pc/meta.go, drivers/189pc/types.go, drivers/189pc/utils.go, drivers/lanzou/driver.go, drivers/lanzou/util.go, go.mod, go.sum
增加一个新的上传接口。
注意：该上传接口需要计算MD5值，并且家庭云不支持覆盖上传
=> fix(189pc):large file upload error

README.md, README_cn.md, drivers/all.go, drivers/dropbox/driver.go, drivers/dropbox/meta.go, drivers/dropbox/types.go, drivers/dropbox/util.go, pkg/utils/slice.go
=> feat: add Dropbox driver

drivers/aliyundrive_share/driver.go, drivers/aliyundrive_share/util.go
add limit rate for aliyundrive_share and lift rate limit restrictions
=> fix(aliyundrive_share): add limit rate for aliyundrive_share and lift rate limit restrictions

drivers/all.go, drivers/mopan/driver.go, drivers/mopan/meta.go, drivers/mopan/types.go, drivers/mopan/util.go, go.mod, go.sum
电信这个云盘的安全问题有点多，不建议存隐私文件。密码也不要使用长用的密码，服务器会明文存储。
该存储的使用注意事项
1. 由于请求加密，暂时未想到合适的获取文件夹ID的方法，所有目前只能设置为-11。
2. ID为-11的目录下的文件夹不能随意删，否则会出现各种bug（如果不打算用官方那些花里胡哨的功能，可以全删了🤔）。
3. 目录下的名为“文件”的文件夹为用户空间，”私密空间“对应的就是私密空间，名为一长串数字的为共享空间（真够随便的）
4.名为相册的文件夹对应相册功能，但直接操作可能会有bug，并且暂无适配相册的计划。
5.目前官方对文件夹删除有bug，等待修复。。。
=> feat: add mopan driver (close #4325)

drivers/thunder/driver.go, drivers/thunder/util.go
=> fix(thunder):upload issues

drivers/pikpak/driver.go, drivers/pikpak/types.go, drivers/pikpak/util.go
=> fix(pikpak):hash calculation and fast upload judgment

README_cn.md, README_ja.md
I created Japanese translated README.
=> Add Japanese README

drivers/123/util.go
fix: https://github.com/alist-org/alist/issues/4834
=> fix: Use APP-side API for 123pan

drivers/terabox/util.go
=> fix(Terabox): slice out of range issue (fix #4858)

drivers/baidu_photo/driver.go, drivers/baidu_photo/utils.go
=> fix(baidu_photo):album download

drivers/baidu_photo/driver.go, drivers/baidu_photo/help.go, drivers/baidu_photo/meta.go, drivers/baidu_photo/utils.go
=> feat(baidu_photo):delete album source file

drivers/123_share/driver.go, drivers/123_share/meta.go, drivers/123_share/types.go, drivers/123_share/util.go, drivers/all.go
"Sharekey" fill in the last paragraph of the sharing link (do not enter .html)
"Sharepassword" fill in the extraction code
Close https://github.com/alist-org/alist/issues/4853
=> Add 123Pan Share

drivers/189pc/help.go, drivers/189pc/types.go, drivers/189pc/utils.go, drivers/baidu_netdisk/driver.go, drivers/baidu_netdisk/meta.go, drivers/baidu_photo/driver.go, drivers/base/upload.go, drivers/mopan/driver.go, go.mod, go.sum, pkg/errgroup/errgroup.go, pkg/utils/file.go, pkg/utils/io.go, pkg/utils/slice.go
给部分存储驱动实现上传进度恢复，没想到腾讯真的可以直接恢复...
群晖的备份居然没法设置超时(#`Д´)ﾉ
=> Feat upload progress recovery

drivers/lanzou/help.go, drivers/lanzou/util.go
=> fix(lanzou):download not find file sgin

drivers/mopan/driver.go, drivers/mopan/meta.go, go.mod, go.sum
魔盘把 -11 这个目录修复了，但还是没修复隐私空间返回密码o(*￣▽￣*)o
1.默认选择个人文件目录
2.增加debug打印目录信息，日志文件搜索 [mopan]
=> fix(mopan):parameter error

drivers/crypt/driver.go, drivers/crypt/meta.go, pkg/utils/str.go
Close https://github.com/alist-org/alist/pull/5109
Close https://github.com/alist-org/alist/issues/5080
=> feat(crypt): enable filename_encoding for advanced users

internal/stream/stream.go, pkg/utils/file.go
fix #5161 
deal Content-Length trouble when webdav put use chucked.
=> fix(webdav): http chunked request invalid

internal/stream/util.go, pkg/http_range/range.go
(cherry picked from commit 18bf64af47e58cc69cdd2e598de9c19538a7bf78)
=> fix(crypt): fix 139cloud hack

drivers/onedrive/util.go, drivers/onedrive_app/util.go
=> 修复：OneDrive 覆盖上传大文件时会失败

drivers/baidu_netdisk/driver.go, drivers/baidu_netdisk/types.go, drivers/baidu_netdisk/util.go, internal/model/obj.go, internal/stream/util.go
百度列表获取的hash是假的，只有通过下载链接才能获取正确hash
error2是由于Content-Type设置错误导致
=> fix(baidu):hash and error:2

drivers/cloudreve/driver.go, drivers/cloudreve/meta.go, drivers/cloudreve/types.go, drivers/cloudreve/util.go
added switch as this slows the list time a lot
=> feat(cloudreve): folder size count and switch

drivers/mopan/driver.go
=> fix(mopan):302 Redirect

drivers/base/client.go
=> fix: retry multipart file reset

drivers/139/driver.go, drivers/139/meta.go, drivers/139/types.go, drivers/139/util.go
- 支持中国移动云盘新版个人云 API（测试与 PC 网页版和手机客户端列出文件一致）
- 支持中国移动云盘新版个人云的 video_preview 方法
- 中国移动云盘存储中的根文件夹 ID 可不填，默认使用根目录。
=> feat(139): support new personal cloud api

drivers/115/driver.go, drivers/115/meta.go
=> feat(115):support 302 redirect

internal/net/request.go
bytes.Buffer Read will change internal offset, shouldn't use RWMutex for Read
=> fix(net): Buf use Mutex

server/static/static.go
在一个进程中，二次加载 index.html 时报错 `index.html not exist, you may forget to put dist of frontend to public/dist`
=> 二次加载 public/dist 资源的问题

drivers/chaoxing/types.go
=> fix(chaoxing): json cannot unmarshal content.uploadDate (close #6119)

server/webdav/prop.go, server/webdav/webdav.go
fix: https://github.com/alist-org/alist/issues/6104
Use `http.TimeFormat` for windows WebDAV
=> Add support for Microsoft WebDAV

.github/workflows/build_docker.yml, .github/workflows/release_docker.yml
7e6522c8 added "Replace dockerfile tag" step modifies Dockerfile.ffmpeg but "Build and push with ffmpeg" currently is useing git context, the change may have no effect.
=> fix(ci): replace dockerfile tag step may have no effect

drivers/ipfs_api/driver.go
=> fix:url escape filename

drivers/115/meta.go
=> fix(115): disable NoOverwriteUpload

drivers/189pc/types.go
=> fix(189pc): FamilyID in FamilyInfoResp struct range overflow

drivers/all.go, drivers/netease_music/crypto.go, drivers/netease_music/driver.go, drivers/netease_music/meta.go, drivers/netease_music/types.go, drivers/netease_music/upload.go, drivers/netease_music/util.go, go.mod, go.sum
close https://github.com/alist-org/alist/issues/5364
打开网页版，扫码登陆后按 F12 打开浏览器控制台，在 Network 里随便找个请求复制 Cookie
只要确保 Cookie 中有截图中红框的两个字段就行，其他不重要
=> feat: add supports for netease music driver

drivers/sftp/meta.go, drivers/sftp/util.go
=> feat(sftp): add suport for passphrase of private key

drivers/pikpak/driver.go, drivers/pikpak/types.go, drivers/pikpak/util.go
- 修复了 `Captcha_Token` 无法正确刷新的问题，
- 改进了 `UserID`的获取方式
---
感谢 @foxxorcat 指出问题所在
=> fix(pikpak): fix captcha_token not refreshing correctly

drivers/halalcloud/meta.go, drivers/halalcloud/util.go
- 修复了 自定义 `AppID`、`AppVersion`、`AppSecret` 字段未能正确生效的 BUG
- 使用官方授权的 `AppID`、`AppSecret`
=> fix(halalcloud): fix some custom fields not taking effect & update appID and appSecret

drivers/halalcloud/driver.go, drivers/halalcloud/util.go
- 增加 `超时时间` ———— 避免因为网络延迟导致的超时问题
=> fix(halalcloud): fix the timeout issue when logging in

drivers/189pc/utils.go
=> fix(189pc): InvalidSessionKey

drivers/pikpak/driver.go, drivers/pikpak/meta.go, drivers/pikpak/util.go
- 修复 初始获取`CaptchaToken`时，`user_id`传入错误
- 添加了 `RefreshTokenMethod` 选择项：`oauth2` | `http` ———— 用户可以选择 令牌刷新的方式
=> fix(pikpak):fix an error when passing the user_id field

drivers/pikpak/driver.go, drivers/pikpak/meta.go, drivers/pikpak/util.go, drivers/pikpak_share/driver.go, drivers/pikpak_share/meta.go, drivers/pikpak_share/util.go
- 修复了 令牌刷新方式选用 `Http`时，`Authorization` 请求头丢失
- 跟随官方最新版本，更新了部分参数
- 为 `Platform` 选择项 添加了 `pc`选项
- 添加了 `UseLowLatencyAddress` 选择项 和 `CustomLowLatencyAddress` 字段
- 尝试 使用 低延迟的下载地址
- 用户可根据自身需要，选择是否开启
- `CustomLowLatencyAddress` 如果留空，则会自动检测延迟最低的下载节点，也可手动填写
- 跟随官方最新版本，更新了部分参数
- 为 `Platform` 选择项 添加了 `pc`选项
- 添加了 `UseLowLatencyAddress` 选择项 和 `CustomLowLatencyAddress` 字段
- 尝试 使用 低延迟的下载地址
- 用户可根据自身需要，选择是否开启
- `CustomLowLatencyAddress` 如果留空，则会自动检测延迟最低的下载节点，也可手动填写
---
**`CustomLowLatencyAddress` 字段 填写说明**
- **如果留空，则会自动检测延迟最低的下载节点，也可手动填写**
- **自动检测延迟最低的下载节点 会使得PikPak驱动初始化时间变长**
- 目前获取到的 官方下载域名
> 	"dl-a10b-0621.mypikpak.com"
"dl-a10b-0622.mypikpak.com"
"dl-a10b-0623.mypikpak.com"
"dl-a10b-0624.mypikpak.com"
"dl-a10b-0625.mypikpak.com"
"dl-a10b-0858.mypikpak.com"
"dl-a10b-0859.mypikpak.com" …
=> feat(pikpak&pikpak_share): add download address delay detection

drivers/pikpak/util.go
=> fix(pikpak): fix nil pointer error

drivers/123/driver.go, drivers/123/util.go
=> 更换123云盘登录接口

drivers/115/meta.go, drivers/115/types.go, drivers/115/util.go, drivers/115_share/meta.go
=> fix 20GB file upload restriction

server/handles/ssologin.go
OIDC now not working under compatibility mode for there are some logical errors.
Test Image: `mmx233/alist:v3.39.4-alpha3` `mmx233/alist:v3.39.4-alpha3-ffmpeg`
=> fix(sso): OIDC compatibility mode

server/ftp/afero.go, server/ftp/fsread.go, server/ftp/fsup.go
Fix 550 Could not access file: driver error: calling GetHandle: object not found
=> fix(ftp-server): work unproperly when base url is not root

server/ftp/fsmanage.go
=> feat(ftp-server): treat moving across file systems as copying

drivers/thunder/driver.go, drivers/thunder/types.go, drivers/thunder/util.go, internal/offline_download/all.go, internal/offline_download/thunder/thunder.go, internal/offline_download/thunder/util.go, internal/offline_download/tool/add.go, internal/offline_download/tool/download.go
- 增加迅雷云盘的离线下载工具，仿照 pikpak 的写法实现
=> feat(thunder): add offline download tool

server/handles/fsmanage.go, server/handles/fsup.go
Add `overwrite existing` option to preventing unintentional data loss.
增加『覆盖已有文件』选项以防止意外的数据丢失。
=> feat(fs): add `overwrite` option to preventing unintentional overwriting

.github/workflows/release_docker.yml, build.sh, internal/bootstrap/config.go, internal/bootstrap/patch.go
Use the development version of the web for beta releases to ensure compatibility between the back-end and front-end.
=> fix(workflow): use the dev version of the web for beta releases

internal/search/util.go
Fix the issue where ignored paths are not updated.
修复『忽略路径』不被正确刷新的问题。
=> fix(index): fix the issue where ignored paths are not updated

drivers/ilanzou/util.go
resolve #7890 
增加 `Accept-Language` 请求头
=> fix(feiji): modify the request header

drivers/189pc/driver.go, drivers/189pc/help.go, drivers/189pc/utils.go, pkg/utils/time.go
修改家庭云转存策略：从创建多个临时文件夹避免文件名冲突改为使用重命名方式避免文件名冲突
=> fix(189pc): transfer rename

internal/archive/zip/utils.go, internal/archive/zip/zip.go, server/handles/archive.go
在解压zip文件过程中解码文件名。
一定程度上优化了文件名编码推测策略。
Close #7988
=> fix(archive): decode filename when decompressing zips

drivers/ilanzou/driver.go
=> chore: fix build failed

server/common/proxy.go
[漏掉RangeReadCloser的处理](https://github.com/AlistGo/alist/pull/7923#issuecomment-2727270560)
=> fix:missing handling of RangeReadCloser

drivers/cloudreve/driver.go, drivers/cloudreve/util.go
修复 alist 上传到 cloudreve 本机存储显示成功，实际失败
Close: #8174
=> fix(cloudreve): enable SetContentLength for uploading to local policy

drivers/alist_v3/driver.go, drivers/alist_v3/meta.go, drivers/alist_v3/types.go, drivers/alist_v3/util.go
支持 AList v3 驱动将压缩文件相关请求转发至驱动后端进行。
=> feat(alist_v3): support forward archive requests

drivers/all.go, drivers/doubao/driver.go, drivers/doubao/meta.go, drivers/doubao/types.go, drivers/doubao/util.go
未实现上传、复制功能
- Cookie：只需 `sid_guard=*******GMT` 即可
- 根文件夹ID：
打开F12->网络，访问 https://www.doubao.com/chat/drive/ ，找到 
https://www.doubao.com/samantha/aispace/homepage 这个请求的 `data.root_id`
或者打开子文件夹，找到 
https://www.doubao.com/samantha/aispace/node_info 这个请求的 `data.node_info.id`
Close: #8020
Close: #2138
Close: #8206
=> feat(doubao): add Doubao driver

drivers/115_open/driver.go, drivers/115_open/upload.go
* support upload huge file
* sequential upload is necessary
=> fix(115_open): support multipart upload

drivers/pikpak/driver.go, drivers/pikpak/util.go, drivers/pikpak_share/driver.go, drivers/pikpak_share/util.go
=> fix(pikpak&pikpak_share): update algorithms

drivers/quark_uc/driver.go, drivers/quark_uc_tv/driver.go, server/handles/fsread.go
1. modified quark_uc and quark_uc_tv driver native proxy to use multithreading;
2. file query return result add the id and path fields;
=> perf(quark_uc&quark_uc_tv): native proxy multithreading

drivers/pikpak/util.go, drivers/pikpak_share/util.go
修复 #8278 遗漏的，对于 `WebPackageName` 的修改
=> fix(pikpak&pikpak_share): fix WebPackageName

drivers/139/meta.go, drivers/139/util.go
原来默认使用small的缩略图，太小了，在某些应用场景太糊了，增加了一个开关用来控制是否返回large的缩略图
=> feat: add UseLargeThumbnail for 139

drivers/123/util.go, drivers/aliyundrive/driver.go, drivers/aliyundrive/meta.go
由于阿里云盘API修改，导致https://api.alipan.com/v2/user/get 无法获取到drive_id 所有修改driveid为用户自己填写。
=> fix: update DriveId assignment to use DeviceID from Addition struct

internal/op/role.go, internal/op/storage.go, internal/op/user.go, server/handles/user.go
=> feat: enhance user creation and storage update with path validation and role integration

README.md, README_cn.md, README_ja.md
- Add API documentation section to `README.md` with link to Apifox
- Add API documentation section to `README_ja.md` with Japanese translation and link to Apifox
- Add API documentation section to `README_cn.md` with Chinese translation and link to Apifox
=> docs(README): Add API documentation links across multiple languages

internal/db/user.go, internal/op/role.go, internal/op/user.go, server/handles/role.go, server/handles/user.go
=> feat(user-management): Enhance admin management and role handling

internal/bootstrap/data/setting.go, internal/conf/const.go
=> feat(ui): add new UI configuration option to settings

drivers/alist_v3/types.go
=> feat(alist_v3): add IntSlice type for JSON unmarshalling

go.mod, go.sum
=> chore(deps): Upgrade 115driver to v1.1.1

server/handles/search.go
=> feat(search): Optimized search result filtering and paging logic

server/handles/user.go
- Imported the `utils` package
- Modified the role assignment logic to prevent assigning administrator or guest roles to users
=> feat(user): Enhanced role assignment logic

internal/op/storage.go
=> Refactor (storage): Comment out the path validation logic
